### ISSUE TITLE
ruby:2.1-alpine update (to alpine 3.5) broke postgresql compatibility, openssl/libressl dependency conflicts

### ISSUE THREAD

**Issue by mdylanbell** [docker-library/ruby#104]
ruby:2.1-alpine has package conflicts after the recent update to alpine 3.5, when using postgresql.

```
ERROR: unsatisfiable constraints:
  openssl-dev-1.0.2j-r2:
    conflicts:
               libressl-dev-2.4.4-r0[pc:libcrypto=1.0.2j]
               libressl-dev-2.4.4-r0[pc:libssl=1.0.2j]
               libressl-dev-2.4.4-r0[pc:openssl=1.0.2j]
    satisfies: .ruby-rundeps-0[openssl-dev]
  libressl-dev-2.4.4-r0:
    conflicts:
               openssl-dev-1.0.2j-r2[pc:libcrypto=2.4.4]
               openssl-dev-1.0.2j-r2[pc:libssl=2.4.4]
               openssl-dev-1.0.2j-r2[pc:openssl=2.4.4]
    satisfies:
               postgresql-dev-9.6.1-r0[libressl-dev]
```

Alpine 3.5 switched from openssl to libressl, but the ruby-rundeps package depends on openssl and the packages conflict.

**Comment by TimonSotiropoulos** [comment]
+1 

I am having the same issue as above. Currently using ruby:2.2-alpine.

**Comment by michetti** [comment]
+1

Same with ruby:2.3.3-alpine, mysql/mariadb:
```
ERROR: unsatisfiable constraints:
  libressl-dev-2.4.4-r0:
    conflicts:
               openssl-dev-1.0.2j-r2[pc:libcrypto=2.4.4]
               openssl-dev-1.0.2j-r2[pc:libssl=2.4.4]
               openssl-dev-1.0.2j-r2[pc:openssl=2.4.4]
    satisfies:
               mariadb-dev-10.1.20-r0[libressl-dev]
  .gems-build-dependencies-0:
    masked in: cache
    satisfies: world[.gems-build-dependencies]
  openssl-dev-1.0.2j-r2:
    conflicts:
               libressl-dev-2.4.4-r0[pc:libcrypto=1.0.2j]
               libressl-dev-2.4.4-r0[pc:libssl=1.0.2j]
               libressl-dev-2.4.4-r0[pc:openssl=1.0.2j]
    satisfies: .ruby-rundeps-0[openssl-dev]
```

**Comment by tianon** [comment]
Sorry folks -- this is definitely going to be reverted.  See https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for further discussion. :disappointed:

**Comment by tmaier** [comment]
Could we not replace `openssl` with `libressl` in the `Dockerfile-alpine.template` and within the `gem/bundle install` commands?

**Comment by tianon** [comment]
@tmaier yes, that would take care of some of the downstream breakage, but not all of it -- there are more examples of breakage linked to/from https://github.com/docker-library/golang/pull/131#issuecomment-270677556, including the `mysql`/`mariadb` breakage above: https://github.com/docker-library/ruby/issues/104#issuecomment-270689055

**Comment by vovimayhem** [comment]
When will the corrected image be available at docker hub?

**Comment by tianon** [comment]
@vovimayhem once https://github.com/docker-library/official-images/pull/2513 is merged, built, and pushed :+1:

**Comment by vovimayhem** [comment]
Got it! Thanks!

**Comment by romdim** [comment]
Hello everyone, I've created this for now:
https://hub.docker.com/r/artwishlist/alpine-3.6-ruby-2.4.1/
https://github.com/Artwishlist/alpine-3.6-ruby-2.4.1
until it's officially supported.

If you use puma, make sure to use 3.6.2 until this is released:
https://github.com/puma/puma/pull/1285

**Comment by romdim** [comment]
https://github.com/puma/puma/releases/tag/v3.9.0 is out
