### ISSUE TITLE
Don't uninstall xz-utils 

### ISSUE THREAD

**Issue by ledermann** [docker-library/ruby#105]
#95 caused a regression: The package `xz-utils` was added to `$buildDeps`, so it gets purged after the build. But because `xz-utils` is already included in `buildpack-deps:jessie`, #95 effectively removes it.

This causes build issues with images based on the Ruby image, if they require `xz`. Example here: https://github.com/ledermann/docker-base/commit/f1ce46a79f54603fe40da72a6dcea21fad483f75

**Comment by tianon** [comment]
Oops!  I'll go make a PR to fix that oversight.  Thanks for the report!
