### ISSUE TITLE
Use ARG instead of ENV for variables

### ISSUE THREAD

**Issue by DarthHater** [docker-library/ruby#111]
It occurs to me that none of the ENV variables really need persisted (maybe the SHA?), so these can likely be changed to ARG instead of ENV. If the intent is to allow someone to figure out what is running in the image, you can perhaps use a label instead? This will be available to docker inspect?

**Comment by yosifkit** [comment]
Same comment as https://github.com/docker-library/tomcat/issues/60#issuecomment-271674272.

**Comment by DarthHater** [comment]
They don't so much cause problems per se, but both can be overrode (you can pass in new values for ENV variables using -e just like you can with ARG and --build-arg) the main difference is that they don't stick around in the container as Environment variables. If they are ephemeral, may as well toss them instead of persisting them. Since these variables are for building the image, not for running it past build, they seem to be a much better fit as ARGs. ¯\_(ツ)_/¯

**Comment by yosifkit** [comment]
`ARG` is not great unless necessary, especially given that it makes the output of docker history unnecessarily difficult to parse for both for humans and for computers.

Related: https://github.com/docker-library/php/issues/698
