### ISSUE TITLE
Wrong sha256 for ruby 2.3.3-alpine

### ISSUE THREAD

**Issue by k2612332** [docker-library/ruby#114]
According to: https://www.ruby-lang.org/en/downloads/ as well as sha256sum utility, it should be 241408c8c555b258846368830a06146e4849a1d58dcaf6b14a3b6a73058115b7 instead of 1a4fa8c2885734ba37b97ffdb4a19b8fba0e8982606db02d936e65bac07419dc

This cause build to fail

**Comment by yosifkit** [comment]
We use the SHA256 from [here](https://www.ruby-lang.org/en/news/2016/11/21/ruby-2-3-3-released/) based on the `tar.zx` file as pulled by the [update script](https://github.com/docker-library/ruby/blob/68b87152172104bdf9359cde9247b99d4d0b1176/update.sh#L49).  You are looking at the `tar.gz` SHA256 sum.
