### ISSUE TITLE
alpine onbuild?

### ISSUE THREAD

**Issue by rmoriz** [docker-library/ruby#115]
How about providing an alpine based "onbuild" flavor?

**Comment by yosifkit** [comment]
I think [this comment](https://github.com/docker-library/python/issues/77#issuecomment-170268467) from python will mostly apply here.  Of course swapping `requirements.txt` with `Gemfile`/`Gemfile.lock`.

The purpose of the `alpine` based image is to be really tiny with no extra dependencies installed. While the onbuild image is just supposed to work with any random `Gemfile` so it needs any common system dependency already installed.
