### ISSUE TITLE
Memory usage and limitation

### ISSUE THREAD

**Issue by mjdavies** [docker-library/ruby#116]
This isn't an issue really, just a call for some help.

We're running a rails app with an image based on FROM ruby:2.3.1

We haven't got a massive AWS node, and are running multiple containers.

I'm trying to limit the amount of memory the ruby containers are using, but not having alot of joy.

If I set the limit to say 200m in like so (docker compose version 2)

mem_limit: 200m

When the container hits 200m, the ruby process is killed and the container stops.

Looking at my docker stats on the node 2 of the rails containers are running at 500MB plus, and they're never giving any memory back, just keep on consuming.

I'm wondering if anyone has any advice on how to handle this in docker and ruby.

Any tips or advice greatly appreciated.

**Comment by yosifkit** [comment]
If it is safe for your app to be killed when it gets too big you could add a restart policy of `always`.  You can disable the oom_killer for a container but that would just make your application fail to allocate memory and I'm not sure how ruby/rails handle that.

Here are a couple random posts on optimizing rails memory usage:
 - http://collectiveidea.com/blog/archives/2015/02/19/optimizing-rails-for-memory-usage-part-1-before-you-optimize
 - https://www.airpair.com/ruby-on-rails/performance

**Comment by mjdavies** [comment]
Hi @yosifkit 

It's a web app so we can't really bomb them out, unfortunately.

Thanks for the links, they look helpful, I'll have a read through them.

Moving ruby/rails apps into docker is proving more challenging than some other apps, I guess it's the nature of ruby itself.  We'll get there though.

**Comment by yosifkit** [comment]
Just a note that if you start using passenger to run your rails application, you'll definitely want something like `tini` in there to reap zombies.  There is an example in the [redmine](https://github.com/docker-library/redmine/blob/8bea4d904978686c8f7f7593b860df435e609603/3.3/passenger/Dockerfile) image, but you can also use `--init` to inject the `tini` reaper automatically if you are on docker 1.13 or greater.

**Comment by mjdavies** [comment]
Thanks for the heads up

I was using unicorn, but looking at using puma now in dev and production sitting behind nginx.

You wouldn't have any experience of setting that up would you @yosifkit ?

**Comment by yosifkit** [comment]
Not really. :disappointed: We use some scripts to help generate our nginx config: https://github.com/infosiftr/nginx-conf.d; not sure if they'd be helpful to you.

**Comment by Moghedrin** [comment]
Seems like it's not an issue with the image here. Issue is stale, so I'm going to go ahead and close this, though if anybody else has this same issues, feel free to pop in and comment and we'll if we can't give more advice. :)
