### ISSUE TITLE
Inconsistency between running local image and on GitLab CI

### ISSUE THREAD

**Issue by rhys-vdw** [docker-library/ruby#118]
Gem binaries fail to be found in GitLab CI, but not in a local install.

There is a discussion of this issue [here](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/2014) including a link to a [minimal reproduction](https://gitlab.com/tmaier/gitlab-ci-issue1). (To trigger the CI failure you must fork the project, click "pipelines" and then create and run a pipeline.)

The issue may lie with `gitlab-ci-multi-runner` but after having a dig around today I am starting to suspect it might have something to do with how bundler is configured in the `ruby:2.3-alpine` and `ruby:2.3` `Dockerfile`s.

I am new to Docker so excuse me if I'm off track here. Either way, perhaps some of you more experienced Ruby/Docker users might be able to help point us in the right direction?

**Comment by yosifkit** [comment]
Some guessing that the `cd` is probably not preserved between `before_script` and `script`. You could drop the `before_script` and try this:

```yaml
  script:
    - cd /usr/src/app && bin/rake -T
```

**Comment by rhys-vdw** [comment]
Thanks for the response, @yosifkit. This [does not appear to be the issue](https://gitlab.com/usabilityhub/gitlab-ci-issue1/builds/10775323). I was wondering if it had something to do with [`$GEM_HOME` being set after `bundle install` is called](https://github.com/docker-library/ruby/blob/17f666371fa5c88c48a38bc53c611f26c7455778/2.3/alpine/Dockerfile#L95-L99)?

**Comment by rhys-vdw** [comment]
@yosifkit I think that there is no problem running `bin/rake -T` btw, I think the script itself calls `Gem.bin_path` which returns an incorrect path (but only in GitLab CI).

**Comment by rhys-vdw** [comment]
> I was wondering if it had something to do with $GEM_HOME being set after gem install bundler is called?

Switching these commands around didn't work either. Still [failing in CI](https://gitlab.com/usabilityhub/gitlab-ci-issue1/builds/10775821), this time with this error:

```
$ cd /usr/src/app
$ bin/rake -T
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from bin/rake:15:in `<main>'
ERROR: Build failed: exit code 1
```

The same command (`rake -T`) will still succeed with the same image on my machine.

**Comment by yosifkit** [comment]
Maybe throw an `env` in the script to print out the variables to see if they are overriding any environment variables that might be confusing bundle/rake?

**Comment by rhys-vdw** [comment]
Thanks again for your responses so far. As I mentioned above I'm uncertain as to the cause of this error and am conscious that I might be wasting your time. If you're confident that this problem is not related to this repository there will be no hard feelings should you close the issue.

> Maybe throw an env in the script to print out the variables to see if they are overriding any environment variables that might be confusing bundle/rake?

I did try this [earlier](https://gitlab.com/usabilityhub/gitlab-ci-issue1/commit/20e3d7d7b585066c209cfd0d89988193ff4cc447). You can see where I've logged the environment variables [here](https://gitlab.com/usabilityhub/gitlab-ci-issue1/builds/10493552).

**All environment variables set in GitLab CI:**
```
CI_BUILD_ID=10493552
CI_SERVER_REVISION=44543a4
RUBY_MAJOR=2.3
CI_BUILD_REF=20e3d7d7b585066c209cfd0d89988193ff4cc447
BUNDLER_VERSION=1.14.3
CI=true
CI_PROJECT_NAME=gitlab-ci-issue1
HOSTNAME=runner-fa6cab46-project-2705776-concurrent-0
CI_SERVER_VERSION=8.17.0-rc2-ee
RUBYGEMS_VERSION=2.6.10
SHLVL=2
OLDPWD=/builds/usabilityhub/gitlab-ci-issue1
PORT=5000
HOME=/root
CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
CI_PROJECT_ID=2705776
CI_REGISTRY_IMAGE=registry.gitlab.com/usabilityhub/gitlab-ci-issue1
BUNDLE_APP_CONFIG=/usr/local/bundle
GITLAB_CI=true
CI_BUILD_REPO=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/usabilityhub/gitlab-ci-issue1.git
CI_PROJECT_DIR=/builds/usabilityhub/gitlab-ci-issue1
CI_PROJECT_PATH=usabilityhub/gitlab-ci-issue1
CI_PROJECT_NAMESPACE=usabilityhub
BUNDLE_BIN=/usr/local/bundle/bin
CI_SERVER_NAME=GitLab
RUBY_VERSION=2.3.3
GIT_STRATEGY=none
CI_RUNNER_DESCRIPTION=shared-runners-manager-3.gitlab.com
PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CI_DEBUG_TRACE=false
CI_BUILD_REF_SLUG=envtest
GITLAB_USER_EMAIL=rhys.vdw@gmail.com
BUNDLE_PATH=/usr/local/bundle
CI_SERVER=yes
CI_BUILD_BEFORE_SHA=20e3d7d7b585066c209cfd0d89988193ff4cc447
CI_RUNNER_ID=44028
CI_REGISTRY=registry.gitlab.com
GEM_HOME=/usr/local/bundle
CI_BUILD_NAME=rake -T custom image
RUBY_DOWNLOAD_SHA256=1a4fa8c2885734ba37b97ffdb4a19b8fba0e8982606db02d936e65bac07419dc
PWD=/usr/src/app
CI_RUNNER_TAGS=shared, docker, linux, ruby, mysql, postgres, mongo, git-annex, east-d, gce
CI_BUILD_REF_NAME=envtest
CI_PROJECT_URL=https://gitlab.com/usabilityhub/gitlab-ci-issue1
CI_PIPELINE_ID=6482660
CI_BUILD_STAGE=test
BUNDLE_SILENCE_ROOT_WARNING=1
GITLAB_USER_ID=715146
```

I pasted the above into `remote_env.txt`, and did the same thing locally and added these files to `local_env.txt`.

Here is a diff of the files:

**Diff of local environment variables and those in the CI:**
```
diff <(sort local_env.txt) <(sort remote_env.txt)
5a6,32
> CI=true
> CI_BUILD_BEFORE_SHA=20e3d7d7b585066c209cfd0d89988193ff4cc447
> CI_BUILD_ID=10493552
> CI_BUILD_NAME=rake -T custom image
> CI_BUILD_REF=20e3d7d7b585066c209cfd0d89988193ff4cc447
> CI_BUILD_REF_NAME=envtest
> CI_BUILD_REF_SLUG=envtest
> CI_BUILD_REPO=https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/usabilityhub/gitlab-ci-issue1.git
> CI_BUILD_STAGE=test
> CI_BUILD_TOKEN=xxxxxxxxxxxxxxxxxxxx
> CI_DEBUG_TRACE=false
> CI_PIPELINE_ID=6482660
> CI_PROJECT_DIR=/builds/usabilityhub/gitlab-ci-issue1
> CI_PROJECT_ID=2705776
> CI_PROJECT_NAME=gitlab-ci-issue1
> CI_PROJECT_NAMESPACE=usabilityhub
> CI_PROJECT_PATH=usabilityhub/gitlab-ci-issue1
> CI_PROJECT_URL=https://gitlab.com/usabilityhub/gitlab-ci-issue1
> CI_REGISTRY=registry.gitlab.com
> CI_REGISTRY_IMAGE=registry.gitlab.com/usabilityhub/gitlab-ci-issue1
> CI_RUNNER_DESCRIPTION=shared-runners-manager-3.gitlab.com
> CI_RUNNER_ID=44028
> CI_RUNNER_TAGS=shared, docker, linux, ruby, mysql, postgres, mongo, git-annex, east-d, gce
> CI_SERVER=yes
> CI_SERVER_NAME=GitLab
> CI_SERVER_REVISION=44543a4
> CI_SERVER_VERSION=8.17.0-rc2-ee
6a34,37
> GITLAB_CI=true
> GITLAB_USER_EMAIL=rhys.vdw@gmail.com
> GITLAB_USER_ID=715146
> GIT_STRATEGY=none
8c39,40
< HOSTNAME=0c9843fb9094
---
> HOSTNAME=runner-fa6cab46-project-2705776-concurrent-0
> OLDPWD=/builds/usabilityhub/gitlab-ci-issue1
10a43
> PWD=/usr/src/app
15c48
< no_proxy=*.local, 169.254/16
---
> SHLVL=2
```

I then tried feeding `remote_env.txt` into `docker run` via `--env-file` to see if I could make the image fail. It still succeeded:

**Running local image with all env vars used in CI:**
```
docker run --env-file=remote_env.txt my_image rake -T
rake my_custom_task  # My task... When this is shown, $ rake -T worked
```

Just as a sanity check I ran:

**Printing environment vars actually set when feeding in copy of GitLab CI vars:**
```
docker run --env-file=remote_env.txt my_image printenv
```

And copied the output into `remove_env_ci.txt`

```
-> diff <(sort local_env_ci.txt) <(sort remote_env.txt)
1d0
50d48
< no_proxy=*.local, 169.254/16
```

So it seems that it will succeed with all the same variables apart from `no_proxy`, which seems unlikely to be used by RubyGems.

I'm not clear on which other settings might be varied between the instances.

**Comment by tianon** [comment]
Sorry for the delay -- I think we probably haven't responded because we're just as stumped as you are.  It seems like either your local environment is doing something weird (and thus shouldn't be working) or GitLab is doing something weird, but since you can't reproduce locally I'm inclined to close.  If you sort it out and figure out that it's an issue with the image, please do let us know! :+1:
