### ISSUE TITLE
Gems go missing

### ISSUE THREAD

**Issue by krainboltgreene** [docker-library/ruby#120]
Things working fine all morning, but then suddenly after changing something in the `lib/` directory of my rails application the container is failing to run due to missing a gem. I `/bin/sh` in and look in gem home and it's right there. I restart the container and now I can't even get it to boot (same reason).

Why does my ruby instance think a gem doesn't exist when it clearly exists?

**Comment by krainboltgreene** [comment]
If I rebuild the container everything is fine.

**Comment by perlun** [comment]
@krainboltgreene please provide more log output for us to be able to analyze the issue easier.
