### ISSUE TITLE
why remove wget?

### ISSUE THREAD

**Issue by wyaeld** [docker-library/ruby#121]
@yosifkit 

The majority of rails projects require installing nodejs, and while I'm not proposing including that, we always have to go through additional steps to apt update, and install wget or curl in order to get anywhere.

Is there a key reason why the base images don't leave something like wget/curl in there, given its overall usefulness for the core ruby/rails use-cases?

ADD can't be used due to the inability to chain commands on it and stop the archive going into the layers

**Comment by tianon** [comment]
As far as I can tell, the image does include `wget`:
```console
$ docker run -it --rm ruby wget --version
GNU Wget 1.16 built on linux-gnu.

+digest +https +ipv6 +iri +large-file +nls +ntlm +opie +psl +ssl/gnutls 

Wgetrc: 
    /etc/wgetrc (system)
Locale: 
    /usr/share/locale 
Compile: 
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc" 
    -DLOCALEDIR="/usr/share/locale" -I. -I../lib -I../lib 
    -D_FORTIFY_SOURCE=2 -I/usr/include -g -O2 -fstack-protector-strong 
    -Wformat -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 
    -g -Wall 
Link: 
    gcc -g -O2 -fstack-protector-strong -Wformat 
    -Werror=format-security -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall 
    -Wl,-z,relro -L/usr/lib -lnettle -lgnutls -lz -lpsl -lidn -luuid 
    ftp-opie.o gnutls.o http-ntlm.o ../lib/libgnu.a 

Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
```

IIRC, it's coming in via `buildpack-deps` (although is probably removed on purpose for the `slim` images to make them as small as possible).

**Comment by wyaeld** [comment]
Hi @tianon you're right, I wasn't being specific enough.  I do mean in the slim image.  wget is under 500Kb though, on a ~270MB or all base.  I'd suggest its not a meaningful saving, and creates quite a bit of inconvenience.

Would you consider a PR to keep from being removed on Slim?

**Comment by Moghedrin** [comment]
If you need `wget` in slim, you could always make a two-line Dockerfile and adding it in. :) Something like the following ought to work:
```
FROM ruby:slim
RUN apt-get update && apt get install -y wget
```

IIRC, this was the type of use case originally intended for the slim variants: they're not going to be useful for a majority of projects out of the box, but rather represent the smallest common base to build from.

I would personally be -1 adding `wget` into slim variants, given that the goal of slim isn't to limit inconvenience. For that, `ruby:2.4` (or whatever version you choose to use) is much more appropriate.

**Comment by wyaeld** [comment]
Clearly we know how to put it back.  The point is that it wastes up to 60 seconds for every build, for no apparent gain.  Arguing that inconvenience is unimportant is irrational.  It's been a big reason for Docker's success, and while not the driving criteria for every decision, its still worth considering.

I'm still waiting on a realistic argument as to why taking it out makes sense.  The other variants have it, the base layer has it, and the removal results in an entire 0.2% reduction in the base image size.  That's not a worthwhile gain.




It should not be necessary to always run apt-get update twice in an image to get to a reasonable place.  The full `ruby` image contains a larger footprint that we don't want.

**Comment by perlun** [comment]
I agree with @wyaeld. The decision to not include a minimal package like `wget` or `curl` needs a stronger motivation.

Does it bring in other library dependencies not already present in the slim image? Here is from `apt-cache show wget` on a Raspbian:

`Depends: libc6 (>= 2.17), libgnutls-deb0-28 (>= 3.3.0), libidn11 (>= 1.13), libnettle4, libpsl0 (>= 0.4.0), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4)`

**Comment by yosifkit** [comment]
Installing wget is a non-trivial amount of space:
```console
$ docker images ruby:slim
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ruby                slim                a3734dcecc58        45 hours ago        224MB
$ docker run -it --rm ruby:slim bash
root@f502656d113f:/# apt-get update
...
root@f502656d113f:/# apt-get install --no-install-recommends wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libgmp10 libgnutls-deb0-28 libhogweed2 libicu52 libidn11 libnettle4 libp11-kit0
  libpsl0 libtasn1-6
Suggested packages:
  gnutls-bin
The following NEW packages will be installed:
  libgmp10 libgnutls-deb0-28 libhogweed2 libicu52 libidn11 libnettle4 libp11-kit0
  libpsl0 libtasn1-6 wget
0 upgraded, 10 newly installed, 0 to remove and 1 not upgraded.
Need to get 8856 kB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] ^C
```

That is a 15% increase in size (installing curl would be a 3% increase), but that is not really the point.

>This image does not contain the common packages contained in the default tag and only contains the **minimal packages needed to run ruby**. Unless you are working in an environment where only the ruby image will be deployed and you have space constraints, we highly recommend using the default image of this repository.
>
> \-  [docs](https://github.com/docker-library/docs/tree/51ce383af36e2d5ee34d4ea208f29c3b6a226b0d/ruby#rubyslim) (emphasis added)

**Comment by radeno** [comment]
If you need nodejs with ruby you can try combination od two official repos
https://github.com/Starefossen/docker-ruby-node
