### ISSUE TITLE
The ruby:2.1.1 image runs ruby 2.1.2

### ISSUE THREAD

**Issue by thomas-profitt** [docker-library/ruby#122]
```
> docker run ruby:2.1.1 ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45867) [x86_64-linux]
```

**Comment by tianon** [comment]
Given that `2.1.10` is the current version, I'm not sure that there's really much we can do with this (there was likely a glitch in the build server that caused the wrong image contents to get tagged with 2.1.1) -- any reason you can't use `2.1.10`?

**Comment by thomas-profitt** [comment]
My project's Gemfile specified ruby 2.1.1, and wouldn't run in the ruby:2.1.1 container because its ruby version is incorrect. For my own use case, my workaround was just removing the ruby version specification.

I agree that this isn't a big issue, but it didn't look like it had been reported before, so here it is.

**Comment by Moghedrin** [comment]
Given that ruby:2.1.1 is no longer a supported official image, I'm going to go ahead and close this issue. It's definitely strange that the wrong image gets tagged with 2.1.1, but as @tianon said, there's not much we can do with this. :)
