### ISSUE TITLE
Displaying Unicode Text in irb

### ISSUE THREAD

**Issue by mvasin** [docker-library/ruby#123]
Displaying unicode text in IRB is broken. Try to put "привет" or "西班牙的雨大多數落在平原上" in IRB.

The issue is described here: https://github.com/cantab/unicode_titlecase/wiki/Displaying-Unicode-Text-in-irb

**Comment by tianon** [comment]
Have you tried including `-e LANG=C.UTF-8` in your `docker run` (or `ENV LANG C.UTF-8` in your `Dockerfile`)?
```console
$ docker run -it --rm -e LANG=C.UTF-8 ruby
irb(main):001:0> 'привет'
=> "привет"
irb(main):002:0> '西班牙的雨大多數落在平原上'
=> "西班牙的雨大多數落在平原上"
irb(main):003:0> 
```

**Comment by mvasin** [comment]
@tianon Thanks, works like a charm!

Are there any reasons not to set LANG environment variable to C.UTF-8 in Dockerfile by default?
