### ISSUE TITLE
ffmpeg missing in ruby:latest ubuntu 16.04?

### ISSUE THREAD

**Issue by wurde** [docker-library/ruby#136]
E: Package 'ffmpeg' has no installation candidate

**Comment by yosifkit** [comment]
`ruby:latest` is currently based on Debian Jessie.  You'd need to add jessie-backports to the apt lists to install `ffmpeg`: https://packages.debian.org/jessie-backports/ffmpeg.

Details on adding backports: https://backports.debian.org/Instructions/
