### ISSUE TITLE
No gcc nor make being installed

### ISSUE THREAD

**Issue by andradei** [docker-library/ruby#138]
Grabbing the image via

`docker pull ruby:2.4.1-slim`

and installing Sass via

```
docker run -ti ruby:2.4.1-slim /bin/bash
root@xxx:/# gem install sass
```

Fails with the following error:

```
ERROR:  Error installing sass:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/ffi-1.9.18/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20170718-6-lgxq44.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/local/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from /usr/local/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
        from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.4.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/ffi-1.9.18 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.4.0/ffi-1.9.18/gem_make.out
```

I realized the image doesn't have `gcc` nor `make` installed. Running a container, installing both, then `gem install sass` works.

It was building fine before this commit 8954b9635b143504e2fa21459cc8ce809d388242, so is it a _bundler_'s new thing?

**Comment by yosifkit** [comment]
Unless you are building the image yourself, the commit you mention is only 17 hours old and has not been added to any of the images on the Docker Hub. That requires a PR to [official images](https://github.com/docker-library/official-images) and the last time the ruby images were pushed to the Docker Hub was 19 days ago.

Were you perhaps sharing a local directory (or COPYing one in) that had the gems already installed?

**Comment by andradei** [comment]
I didn't realize that. That makes me more confused. My Dockerfile was

```
FROM ruby:2.4.1-slim
RUN mkdir /assets
VOLUME /assets
RUN gem install sass
ENTRYPOINT ["sass"]
```

And it stopped working yesterday on all projects where it was used, until I added this `RUN` directive:

```
RUN apt-get update &&\
  apt-get install -y --no-install-recommends gcc make &&\
  gem install sass
```

While this fixed the issue for me, I still don't know why things broke suddenly.

**Comment by md5** [comment]
@andradei The issue appears to be something introduced in the 3.5.x versions of the `sass` gem, which were released in the last couple weeks. This works fine:

```Dockerfile
FROM ruby:2.4.1-slim
RUN gem install sass -v 3.4.25
```

**Comment by andradei** [comment]
Very subtle stuff. Thanks for finding that out.
Maybe a future version will go back to not requiring `gcc` and `make`.

**Comment by andradei** [comment]
So to be clear (and to close this issue), the _slim_ images don't have `gcc`, `make` (and other tools used to install `ruby` itself) present on its final form. That's by design. `sass`, prior to 3.5.x, didn't require `gcc` and friends. Now it does.

**Comment by md5** [comment]
@andradei That appears to be the case

**Comment by md5** [comment]
To be more precise, `sass` 3.5.0 and higher now have a declared dependency on `sass-listen` (which is a fork of the `listen` gem). This gem, in turn depends on `rb-inotify`, which depends on `ffi`. The build failure you're seeing is actually for `ffi`.

 See https://github.com/sass/sass/issues/1997 for the addition of `sass-listen` as a dependency for `sass`.
