### ISSUE TITLE
Install a dummy package to prevent other Ruby interpreters from being installed

### ISSUE THREAD

**Issue by md5** [docker-library/ruby#139]
We've run into some cases where packages we want to install (e.g. `passenger`) require a Ruby interpreter (via the virtual `ruby-interpreter` dependency on Debian). It would be cool if a dummy package were installed in the Debian-based images that `Provides: ruby-interpreter` to prevent other Ruby interpreters from being installed.

There is also the [`rubygems-integration`](https://packages.debian.org/jessie/rubygems-integration) package under Debian, which could be cool to integrate with as well. I haven't looked at that package closely enough to understand what the integration would look like.

Aside from Debian, it might be nice to do something similar for Alpine as well.

**Comment by md5** [comment]
Another option could be to create an actual Debian or Alpine package on the fly for the bits being installed via `make install`, but I'm not sure that's worth the effort.

**Comment by tianon** [comment]
Copying from https://github.com/docker-library/ruby/issues/336:

---

> Similar to docker-library/php#542

---

> This is somewhat reasonable, but I worry that we're solving a problem that doesn't appear to be as common as it does in the PHP community?
>
> In the PHP case, we added that specifically because we kept getting reports of and seeing users installing php-foo and expecting that it would somehow work -- we don't see very many similar reports in the Ruby community (probably because installing Ruby extensions is generally more straightforward vs the hackery we did with docker-php-ext-* in the PHP world due to limitations in how PHP itself is developed).

---

> I agree that it's not very common. I only spotted it [here](https://github.com/danmunn/redmine_dmsf/issues/329)/[here](https://github.com/danmunn/redmine_dmsf/issues/769).
