### ISSUE TITLE
Bundle without development/test?

### ISSUE THREAD

**Issue by artemave** [docker-library/ruby#14]
Is it possible?

**Comment by fagiani** [comment]
@yosifkit is it possible to use the `onbuild` passing the `BUNDLE_WITHOUT` somehow? It looks like nothing can be set before the `FROM` statement within a Dockerfile. So something like this won't work:

```
# Dockerfile

ARG build_without=""
ENV BUILD_WITHOUT ${build_without}
FROM ruby:2.2.2-onbuild
...

$ docker build --build-arg bundle_without="development test" -t myapp:latest .
```

If I then invert the order, then the `bundle install` command is run before the `ENV` gets set... Are there any clues to achieve this or any other recommended approach?

Thanks!

**Comment by yosifkit** [comment]
@fagiani, I would suggest to just not use the onbuild images, since there is no way to do anything in your Dockerfile before the onbuild triggers: https://github.com/docker-library/ruby/issues/85#issuecomment-242798342.
