### ISSUE TITLE
Any plans to update to alpine 3.6?

### ISSUE THREAD

**Issue by Paxa** [docker-library/ruby#141]
There are some bugs in alpine 3.4 that were fixed in 3.6, especially `resolv.conf` when running in kubernetes

**Comment by tianon** [comment]
See also https://github.com/docker-library/ruby/pull/103, https://github.com/docker-library/ruby/pull/108, and https://github.com/docker-library/golang/pull/131#issuecomment-270677556 for where a change from 3.4 to 3.5 was made previously, where it was reverted, and the discussion that led to the revert. :disappointed:

In some images, we've been adding explicit `alpine3.6` variants, but we haven't looked into anything like that in `ruby` yet.
