### ISSUE TITLE
ruby:alpine points to Alpine 3.4 even though the latest is 3.6

### ISSUE THREAD

**Issue by envygeeks** [docker-library/ruby#148]
```
jordon@sexy ~/development/jekyll/docker (master * u+6) → docker run --rm -it ruby:alpine sh
/ # cat /etc/issue
Welcome to Alpine Linux 3.4
Kernel \r on an \m (\l)
```

**Comment by yosifkit** [comment]
> -	[`2.4.1-alpine3.4`, `2.4-alpine3.4`, `2-alpine3.4`, `alpine3.4`, `2.4.1-alpine`, `2.4-alpine`, `2-alpine`, `alpine` (*2.4/alpine3.4/Dockerfile*)](https://github.com/docker-library/ruby/blob/135c84979b1401a6963e75f3c95161bfe5be2336/2.4/alpine3.4/Dockerfile)
>
> \- from [docs](https://github.com/docker-library/docs/tree/51ce383af36e2d5ee34d4ea208f29c3b6a226b0d/ruby#supported-tags-and-respective-dockerfile-links)

Correct! The default alpine variant is still 3.4 in order to not break users.  You need to use `ruby:alpine3.6` to get 3.6.
