### ISSUE TITLE
Add 2.3.5 and 2.4.2

### ISSUE THREAD

**Issue by cabello** [docker-library/ruby#154]
These releases contain security fixes.

https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/

Please and thank you 😃

**Comment by tbsvttr** [comment]
+1

**Comment by mbrinkme** [comment]
+1

**Comment by wirsslinger** [comment]
+1

**Comment by yosifkit** [comment]
The automated `update.sh` job is currently running (see the bottom of the [readme](https://github.com/docker-library/ruby/commit/083a412b5d9da36614b02e36bae39518f7948f04)).  Once that finishes we can make the PR to official images.

Duplicate issues: #152 #153 #154 #156 #157.
