### ISSUE TITLE
Ruby Security Updates 2.4.2/2.3.5/2.2.8

### ISSUE THREAD

**Issue by ZachBeta** [docker-library/ruby#157]
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-2-8-released/

All released yesterday.

I tried cloning and running the `update.sh` script which failed on my machine, rather than shave that yak, I created this issue. I assume it's probably a quick update for whoever normally does it.

**Comment by ZachBeta** [comment]
And somehow digging thru I didn't see that the commit went out 9 hours ago.
DOH!

**Comment by ZachBeta** [comment]
Though it's not reflected in the docker-library or pull requests
https://github.com/docker-library/official-images/blob/master/library/ruby

**Comment by yosifkit** [comment]
The automated `update.sh` job is currently running (see the bottom of the [readme](https://github.com/docker-library/ruby/commit/083a412b5d9da36614b02e36bae39518f7948f04)).  Once that finishes we can make the PR to official images.

Duplicate issues: #152 #153 #154 #156 #157.

**Comment by ZachBeta** [comment]
Thank you!
