### ISSUE TITLE
Build 2.3.5 Dockerfile

### ISSUE THREAD

**Issue by felicianotech** [docker-library/ruby#158]
Hi,

I see that the 2.4.2 release has been commit [here](https://github.com/docker-library/ruby/commit/beb05c8c3c694e4527effe3e3623120486d0e5ed) but haven't seen anything for the Ruby v2.3.5. release, which was the same day.

Friendly bump. =)

**Comment by yosifkit** [comment]
The automated `update.sh` job is currently running (see the bottom of the [readme](https://github.com/docker-library/ruby/commit/083a412b5d9da36614b02e36bae39518f7948f04)).  Once that finishes we can make the PR to official images.

Duplicate issues: #152 #153 #154 #156 #157.

**Comment by felicianotech** [comment]
Thanks. I'll make sure to check closed issues next time as well.
