### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by mshappe** [docker-library/ruby#159]
This is happening for 2.3.5(-jessie) images, even tho' the web site says the tag is available.

**Comment by yosifkit** [comment]
Correct, some arches build faster than others and so the new tags get updated with only the arches that have finished building (in this case `s390x` is super fast :smile:).  It looks like `amd64` images have finally finished building and pushing, but the aggregating job only runs once per hour.  I'll go trigger it now and the `amd64` versions should be on the manifest list shortly in `library/`.

Side note: we are thinking of ensuring that the manifest list only gets pushed once a specific set of architectures are ready, but that logic has not been started.

**Comment by mshappe** [comment]
Thank you. I would argue that the library page should not announce tags are available until they're available for **all** architectures, but I'm prepared to believe that's impractical.

**Comment by tianon** [comment]
Yeah, you're not wrong -- we have a TODO item in progress since this
massive multiarch update to add support for something like that, but it's
very much non-trivial to implement (especially given that we have some
architectures which build _very_ slowly, like all the arm32 variants).

**Comment by mshappe** [comment]
@tianon Yeah, that's why I was willing to believe it impractical :-) Anyway, thanks!

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
