### ISSUE TITLE
2.4.2-alpine3.6 contains useless ruby libs in `/usr/lib`

### ISSUE THREAD

**Issue by ojab** [docker-library/ruby#160]
Even though `ruby` from `/usr/local` is used, image contains additional ruby libraries in `/usr/lib`:  
```
$ docker run --rm -ti ruby:2.4-alpine3.6 du -csh /usr/lib/ruby /usr/lib/libruby.so.2.4.2
10.1M   /usr/lib/ruby
2.1M    /usr/lib/libruby.so.2.4.2
12.2M   total
```
AFAIU they are not used at all and can be safely removed.

**Comment by yosifkit** [comment]
Duplicate of https://github.com/docker-library/ruby/pull/131.
