### ISSUE TITLE
Consider extracting Ruby installation to script

### ISSUE THREAD

**Issue by omerlh** [docker-library/ruby#168]
I had to create Docker images that have both NodeJs and Ruby (or dotnet and Ruby). So I extracted from the official image a shell script that installs Ruby. I put this script in a [Gist](https://gist.github.com/omerlh/cfe6394754788b2b0b9f836c6c238be7) so I could easily reuse it. Is it possible to use this script also in the official image? It will make more sense to have it here.

**Comment by yosifkit** [comment]
Unfortunately not useful to us; we value clarity rather than brevity. See https://github.com/docker-library/official-images/tree/375e169fd6490590aa45054e20df69a07bacf41b#clarity.

**Comment by omerlh** [comment]
Make sense, thanks!
