### ISSUE TITLE
Isn't bundler _bundled_ with ruby?

### ISSUE THREAD

**Issue by MrOutis** [docker-library/ruby#169]
https://blog.jetbrains.com/ruby/2017/10/10-new-features-in-ruby-2-5/

https://github.com/docker-library/ruby/blob/6959194971f4f84e9bef2976ae6b8a469fa58dae/2.5-rc/alpine3.6/Dockerfile#L97

**Comment by tianon** [comment]
Yep, see the discussion on https://github.com/docker-library/ruby/pull/165#issuecomment-338772831.
