### ISSUE TITLE
Bundler 1.16.0 specific bug in latest images

### ISSUE THREAD

**Issue by eric-hu** [docker-library/ruby#171]
Hi there!

It looks like the latest image releases include Bundler 1.16.0, which introduces [a LoadError in some cases](https://github.com/bundler/bundler/issues/6144#issuecomment-341658101) when bundled gems are installed using `--deployment` or `--path`.  This affects some tools like `rails test`, even with `bundle exec`. This issue isn't in the last version of bundler, 1.15.4.  Is this worth releasing a new set of images with Bundler pinned to 1.15.4?

Disclosure: I work for CircleCI and we build a set of images on top of this one for our customers to use.

**Comment by tianon** [comment]
Any idea how broad the impact is?  Is this something a _lot_ of users are
running into, or just a subset exercising this particular code path in the
new Bundler's deps?

**Comment by yosifkit** [comment]
If we commit an older version, the [update script](https://github.com/docker-library/ruby/blob/58d779d22b18c4a5daad0fb0f11cf81f12a00cba/update.sh) will just bump it again when the jenkins job runs. :cry:

You might be interested in [repo-info](https://github.com/docker-library/repo-info) and specifically the git history of the items in the [ruby/remote](https://github.com/docker-library/repo-info/tree/master/repos/ruby/remote) directory. That can give you a sha256 image id that can be used to pin to a specific past version of the ruby image. So, following the blame history on line [54](https://github.com/docker-library/repo-info/blame/3c3e646729201f0daaaed494272ed1d5f22c2b72/repos/ruby/remote/2.4.md#L54) of `2.4.md` I can get an image that has bundler `1.15.4`: 

```console
$ docker pull ruby@sha256:eed291437be80359321bf66a842d4d542a789e687b38c31bd1659065b2906778
sha256:eed291437be80359321bf66a842d4d542a789e687b38c31bd1659065b2906778: Pulling from library/ruby
85b1f47fba49: Pull complete 
5409e9a7fa9e: Pull complete 
661393707836: Pull complete 
1bb98c08d57e: Pull complete 
19be186d87ce: Pull complete 
e2cab977990a: Pull complete 
c78086f6e123: Pull complete 
Digest: sha256:eed291437be80359321bf66a842d4d542a789e687b38c31bd1659065b2906778
Status: Downloaded newer image for ruby@sha256:eed291437be80359321bf66a842d4d542a789e687b38c31bd1659065b2906778
$ docker run -it --rm ruby:2.4@sha256:eed291437be80359321bf66a842d4d542a789e687b38c31bd1659065b2906778 bundler --version
Bundler version 1.15.4

```

From [this](https://github.com/docker-library/repo-info/blob/e6038d832a1aeddcc7363350b224f55c4da31233/repos/ruby/remote/2.4.md) version of the `2.4.md` file.

**Comment by vovimayhem** [comment]
I've been having trouble with bundler + rubygems for the past hours. Looks it's directly related to these two issues:

* https://github.com/bundler/bundler/issues/6148
* https://github.com/rubygems/rubygems/pull/2065

Rubygems version 2.7.2 has just been released a couple of minutes ago :)

**Comment by eric-hu** [comment]
> Any idea how broad the impact is?  Is this something a _lot_ of users are
running into, or just a subset exercising this particular code path in the
new Bundler's deps?

For now I'm seeing this in limited subset of our Ruby-docker users.  We've only had users report an issue with `rails test` so far.  Someone reported `cucumber` failing in the same way [in this bundler issue](https://github.com/bundler/bundler/issues/6147).  In both cases, it failed with or without`bundle exec`.

There's also an [issue on Rubygems](https://github.com/rubygems/rubygems/issues/2055) with someone reproducing it using a short Ruby script.  My coworker informed me that the Rails team pinned [Bundler < 1.16.0](https://github.com/rails/rails/commit/b106242f52272c4a5ced7a0e9d1dcb1b50542501) as it killed their `bundle install` on CI.  That instance isn't related to this repo though, since they aren't building on top of Docker.  Still, I take it as a sign of how problematic Bundler 1.16.0 is.

--

@yosifkit I didn't know about repo-info, that looks like it could be really helpful in cherry picking around this.  Thanks!

**Comment by eric-hu** [comment]
@vovimayhem My rails reproduction of this issue with minitest, Rubygems 2.7.2 and Bundler 1.16.0 still fails using `bundle exec rails test` :(

**Comment by vovimayhem** [comment]
@eric-hu You mean this one?
```
# script.rb
require 'bundler/setup'
system('bundle exec whatever')
```
Let me check it...

**Comment by vovimayhem** [comment]
@eric-hu Do you have a sample Gemfile + lock for me to try? I'm running the script in one on my projects, but I don't see anything unexpected (other than some version of `rake` not being installed):

```
# Input:
docker run --rm -ti -v $(pwd)/some-project:/usr/src -w /usr/src ruby:2.4.2-alpine ruby ./script.rb

# Output:
Could not find rake-12.0.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by eric-hu** [comment]
@vovimayhem I was doing some testing on a private repo.  I've cloned it to a public one, here you go:
https://circleci.com/gh/eric-hu/bundler-error-demo/1

Repo: https://github.com/eric-hu/bundler-error-demo/tree/master

The rake error is the one.  As you can see on CircleCI, Rake is installed with `bundle install`.  I think you were onto something with Rubygems 2.7.2. Bundler appears to be _less_ broken compared with Rubygems 2.7.1.

**Comment by vovimayhem** [comment]
@eric-hu It is expected that running the script installs missing gems? I ran `bundle install` and everything went fine! (I was using the alpine version, and having gems like `nokogiri` and `pg`, I had to install the "build" packages for it to work, but that's something I expected... you should not have to do this when using a debian-based image)

I'll check your demo now...

**Comment by eric-hu** [comment]
@vovimayhem for that repo, the problem isn't on `bundle install`.  `bundle install` runs fine, but `bundle exec rails test` says Rake isn't installed when `bundle install` showed it was.  This is the specific code path I was referring to earlier.  I've read in one of the related issues that this also only happens with `BUNDLER_APP_CONFIG`.  I think that's necessary for this docker image?

**Comment by vovimayhem** [comment]
@eric-hu I noticed several things on your project CI configuration:

1: It's actually using the `circleci/ruby:2.4.2-node-browsers` as the ruby image, which isn't based (obviously) on my local, fixed image. **If** #172 gets accepted and the official image is re-built & published, the CircleCI guys will still need to rebuild/update their image (perhaps it is an automated build?)

2: Your'e uninstalling `bundler`, updating `rubygems`, and in the next step installing `bundler` again. I tried this exact stuff before, and it didn't work - I had similar issues in an unconsistent manner. This is the exact thing #172 fixes.

I ran your project locally using images built from #172, manually following the steps in your CircleCI config, and didn't observe problems with it at all.

**Comment by vovimayhem** [comment]
(@eric-hu Didn't noticed your'e one of the CircleCI guys)

On a possibly related note, I do remember having problems with `rake` versions not too long ago (maybe some gems requiring another version?), but then I stopped observing them - I assumed they all got sorted out eventually.

It didn't pose a problem during those days, as I'm used to add an entrypoint script in all our rails projects that checks for missing dependencies and installs them automatically...

**Comment by jchesterpivotal** [comment]
We observed a similar (possibly the same) issue with 1.16, which broke our CI builds: https://github.com/bundler/bundler/issues/6162

**Comment by eric-hu** [comment]
@vovimayhem @yosifkit I see from #172 that `master` of this repo now uses Rubygems 2.7.2.  I created a CI workflow and build this image, then ran it against my Rails test suite here:

https://circleci.com/workflow-run/f647789d-80e1-4645-9e11-31a0936ceb0c

It looks like the issue is still a bundler 1.16.0 error.

>It didn't pose a problem during those days, as I'm used to add an entrypoint script in all our rails projects that checks for missing dependencies and installs them automatically...

The problem with this bundler bug isn't that a dependency isn't satisfied.  You can see the dependencies are met because the `bundle exec rspec` command runs and finishes successfully. 
 The bundle doesn't load properly under certain conditions, like when `bundle exec rails test` runs.  This is due to that command attempting to start Spring, and Spring not having access to the full bundle.

**Comment by vovimayhem** [comment]
Was the fix pushed to the docker hub? I see at https://hub.docker.com/_/ruby/ that the last push was 9 days ago... I'm not sure if the images available for downloading have rubygems 2.7.2

**Comment by tianon** [comment]
Yeah, rubygems 2.7.2 went up in https://github.com/docker-library/official-images/pull/3698, merged yesterday. :+1:

**Comment by yosifkit** [comment]
Bundler has since been updated to 1.16.1; this should be fixed now.
