### ISSUE TITLE
Make ruby 2.3.6 available

### ISSUE THREAD

**Issue by kwent** [docker-library/ruby#175]
Hi,

https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/

Regards

**Comment by yosifkit** [comment]
Once the automatic update script runs, we'll work on the PR to official-images.

**Comment by tianon** [comment]
https://github.com/docker-library/ruby/compare/6ad601794e...c7145524ca

**Comment by ojab** [comment]
This can be closed, I assume?
