### ISSUE TITLE
Archive for old Ruby images (beyond EOL)?

### ISSUE THREAD

**Issue by delner** [docker-library/ruby#179]
Hey folks, just a general question in regards to accessing images that are beyond their EOL: **Is it possible to access old versions of images (e.g. 1.9.3, 2.0, 2.1, etc...) that are beyond their support lifetime, that were previously available in this repository?**

I ask because a number of repositories I've worked with are based on these official Ruby images. However, when these older Ruby images are officially removed from support, it makes said applications unusable when the image name no longer resolves.

Your only options are thus 1) update your application to a newer version of Ruby (usually not feasible for larger enterprise applications), 2) find someone else's custom built version of an old Ruby image (not very secure/reliable), or 3) write your own Ruby image to do exactly what the (now removed) old version of the official Ruby image used to do.

The last of these options, though probably best of the 3, creates a lot of fragmentation among community images, and discourages authors of new Docker-based applications from using official images if the official image is just going to eventually be dropped from support and break their applications anyways.

I understand that since these older images are beyond the EOL contract set by the Ruby maintainers, its unreasonable to expect ongoing maintenance, patches or other updates. But is possible/reasonable have access some old version in an "archived" state? With the implication that there's no additional support for them? So legacy applications can continue to function?

**Comment by delner** [comment]
Okay, maybe I'm just crazy. I swore I saw it not working before, but I did just build an image with `FROM ruby:1.9.3` and it seemed to start downloading/building, so I guess this does work?

Is there some kind of confirmation that the old images will continue to be available by their old tags? (Like I'm evidently seeing?)

...my apologies, if this is a total non-issue!

**Comment by yosifkit** [comment]
Yes, anything we have previously built should work to just `docker pull` them. We do not delete old tags from Docker Hub, so they will continue to be available even though they do not show up in the "Supported Tags" section of the readme. They often may not even show up on the [tags page](https://hub.docker.com/r/library/ruby/tags/) since it doesn't support paging (I believe there was a way to use the api to step through the pages).

**Comment by ms-ati** [comment]
...should this issue be closed then? (asking as someone new to this repo)

**Comment by tianon** [comment]
Yeah, thanks @ms-ati :smile:
