### ISSUE TITLE
remove /root/.gem/ ?

### ISSUE THREAD

**Issue by stevecrozz** [docker-library/ruby#184]
Is it necessary to ship these images with /root/.gem/?

I noticed this file is present in all of the alpine images and contribute a good chunk to the image size:
```
~ $ docker run --rm -it ruby:2.2-alpine du -hs /root/.gem/
11.6M	/root/.gem/
~ $ docker run --rm -it ruby:2.3-alpine du -hs /root/.gem/
11.7M	/root/.gem/
~ $ docker run --rm -it ruby:2.4-alpine du -hs /root/.gem/
11.7M	/root/.gem/
~ $ docker run --rm -it ruby:2.5-alpine du -hs /root/.gem/
11.7M	/root/.gem/
```

**Comment by tianon** [comment]
Nope, I think this is just an oversight!  Removing it at build time makes a
lot of sense IMO.

**Comment by stevecrozz** [comment]
Mind if I put in a PR for that then?

**Comment by tianon** [comment]
Yeah, that'd be great!

**Comment by stevecrozz** [comment]
cool. @tianon should we do it on all the images? or just alpine ones?

**Comment by tianon** [comment]
If all the images have this directory, then we should definitely clean it
up in all of them (or figure out what flags we need to pass to whatever
command is creating it so that it doesn't do that anymore).

**Comment by stevecrozz** [comment]
I was looking for a modifier to do that, but didn't find one. Definitely would be interested if anyone else can find that option. This file appears when we run `gem update --system`. Barring that, I'll add a `rm -r /root/.gem/` at the end of the `&&` chain.

**Comment by stevecrozz** [comment]
@tianon Changes are in. The PR is ready for review.
