### ISSUE TITLE
arch 386 only?

### ISSUE THREAD

**Issue by EugenMayer** [docker-library/ruby#187]
When compiling a golang app using `GOARCH=amd64 GOOS=linux` under `golang:1.9` ( any ) the app cannot run under 2.6-stretch due to the arch, compiling with `GOARCH=386` fixes this.

Looking at the dockerfile, i cannot find a reason for that?

**Comment by yosifkit** [comment]
This is the issue tracker for problems with the ruby image.  I'm not sure where your golang issue applies here.

**Comment by EugenMayer** [comment]
@yosifkit are you serious? Ok, if you do not bother reading, why even interact. No offense if you have time, but do you really think i missed that point?

Goodness - make yourself a medal - you just closed an issue. As fast a possible.

**Comment by tianon** [comment]
@EugenMayer this is the issue tracker for the `ruby` official image -- according to your comment, your issue is regarding the `golang:1.9` image
