### ISSUE TITLE
Recent rubygems upgrade has a broken path

### ISSUE THREAD

**Issue by mvisonneau** [docker-library/ruby#212]
I believe that following the recent rubygems upgrade (395cce4eba52917eb9a40c72d50703a1ce9e1acd), the default path for gems binaries is now incorrect. It used to be `/usr/local/bundle/gems/bin` and now is `/usr/local/bundle/bin`

**Comment by mvisonneau** [comment]
my bad, didn't see that #209 was there 🙈

**Comment by yosifkit** [comment]
Fixed by #209.
