### ISSUE TITLE
cannot use postgres-client-10 in ruby:2.4.4 image

### ISSUE THREAD

**Issue by altblanc** [docker-library/ruby#215]
For several reasons, our project should do `apt-get install postgres-client-10` in ruby docker container, but can not do with the current ruby:2.4.4 image.
I can do this with the image created two weeks ago.
![2018-05-25 15 49 07](https://user-images.githubusercontent.com/30380831/40530483-f46ac56c-6033-11e8-97d4-5a94010c67ce.png)

**Comment by yosifkit** [comment]
I would guess this is because the default images have moved from `jessie` to `stretch` (see https://github.com/docker-library/ruby/pull/210).  Perhaps you need to either use `ruby:2.4.4-jessie` or switch your postgres apt url to use their `stretch` repo.

**Comment by altblanc** [comment]
@yosifkit I switch postgres apt url to `stretch` repo, and it worked well! thanks for your help!
