### ISSUE TITLE
Proposal: ONBUILD COPY Gemfile* *.gemspec /usr/src/app/

### ISSUE THREAD

**Issue by tianon** [docker-library/ruby#22]
Docker 1.3.0+ now supports wildcards in `COPY`, so this becomes possible:
```Dockerfile
ONBUILD COPY Gemfile* *.gemspec /usr/src/app/
```

What I propose is that we switch the `onbuild` variants to use this, and add a new `legacy-onbuild` variant for folks who are stuck on < 1.3.0, which just has the current support.

This would solve/deprecate the need for #19, too.

**Comment by eik3** [comment]
just ran into this: I wanted to dockerize a project that has "gemspec" in the Gemfile.
Is there a workaround to get it working with this docker image?

**Comment by yosifkit** [comment]
@eik3, the easy way is to not use the onbuild image and just copy those commands (minus the `ONBUILD`) to your Dockerfile and add in your customizations.

**Comment by odigity** [comment]
FYI -- I just ran into the same problem as @eik3.  Started working on my first gem, tried to use the docker onbuild image, and it failed because the .gemspec wasn't copied along with the Gemfile.

**Comment by tianon** [comment]
Hmm, our minimum supported Docker version is now 1.6+.  @yosifkit do you think this is a change worth considering now?

**Comment by tianon** [comment]
(The `onbuild` variants are discouraged, but this change should be reasonably harmless for existing users.)

**Comment by yosifkit** [comment]
I am going to go with nope.  This will just lead to more reports of `onbuild` tags not doing everything for everyone, since other files within the app can be referenced from a gemspec: https://github.com/cpuguy83/docker-jruby/pull/3#issuecomment-72680471

**Comment by tianon** [comment]
Good point.  Fair enough!
