### ISSUE TITLE
Ruby 2.3.6

### ISSUE THREAD

**Issue by EricRoos** [docker-library/ruby#220]
How can I get Ruby 2.3.6 installed?

I also have a rails app that requires Bundler 1.10.6 and this seems impossible after 2 days of struggling.

Any guidance?

**Comment by tianon** [comment]
Is there something wrong with 2.3.7 that makes it insufficient?  2.3.6 isn't supported (by Ruby upstream or by us), so using it isn't a real great plan.

Regardless, we don't delete old tags, so you should be able to pull `ruby:2.3.6` and get the older version.  To get older bundler, you'll probably have to explicitly remove the bundler included in the image (and/or convince `gem install` to force overwrite it).

**Comment by EricRoos** [comment]
Hard work requirement of 2.3.6. This is a non negotiable. 

When I pulled in 2.3.6 ruby --version returned 2.3.7.

**Comment by EricRoos** [comment]
And the issue with bundler it seems that the bin file that gets generated keeps trying to call the 1.16.x version.

**Comment by tianon** [comment]
I can't reproduce the first issue:

```console
$ docker pull ruby:2.3.6
2.3.6: Pulling from library/ruby
f2b6b4884fc8: Already exists 
4fb899b4df21: Already exists 
74eaa8be7221: Already exists 
2d6e98fe4040: Already exists 
638a4a258268: Pull complete 
3aae84250a19: Pull complete 
16dbfde3ef5f: Pull complete 
Digest: sha256:139ecd159fb74b1de1b1645b17cb7297bcdacee92aed8cdd0c1ada03eb9af994
Status: Downloaded newer image for ruby:2.3.6

$ docker run --rm ruby:2.3.6 ruby --version
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
```

However, it seems like your best bet from here would be to take our `Dockerfile` and modify it to suit your needs directly (since you have pretty specific requirements) -- that way you can explicitly install 2.3.6 and Bundler 1.10.6 right from the start.

**Comment by EricRoos** [comment]
Not sure what i was experiencing earlier. but this is right on. Thank you.

This has been my conclusion as well. Thank you for the prompt reply and help. I'll open another issue if I still have problems with bundler.
