### ISSUE TITLE
ruby:head image

### ISSUE THREAD

**Issue by bquorning** [docker-library/ruby#222]
Besides the latest official releases (plus release candidates), for some projects it is nice to also test against the current master branch.

Would you be interested in releasing a regularly updated ruby:head Docker image?

**Comment by tianon** [comment]
Unfortunately, I think the update frequency will just be way too high -- I also don't think the Ruby project publishes official "snapshots" that they expect users to test regularly, do they?

So, for this repo, the maintenance burden would be way too high, but there's really nothing stopping a motivated user from taking our `Dockerfile` and making the minor adjustments to pull development snapshots instead of explicit releases (it shouldn't be too hard to do so). :+1:

**Comment by bquorning** [comment]
On [ruby-lang.org](https://www.ruby-lang.org/en/downloads/) you can download “stable” and “nightly” snapshots:

>Stable Snapshot: This is a tarball of the latest snapshot of the current stable branch.
>Nightly Snapshot: This is a tarball of whatever is in SVN, made nightly. This may contain bugs or other issues, use at your own risk!

I don’t know how many projects really need to test on a snapshot version of Ruby, but I wanted to do it on the RuboCop gem (see https://github.com/rubocop-hq/rubocop/pull/5767#issuecomment-400071935). I think that project is complicated enough that it might catch edge case bugs in Ruby, which we could then point out to the Ruby core team.

> there's really nothing stopping a motivated user from taking our `Dockerfile` and making the minor adjustments to pull development snapshots instead of explicit releases

I’ll consider doing that 😃

**Comment by bquorning** [comment]
Thank you for the challenge 😄 I am now building daily an image from the Ruby “Nightly Snapshot”.

The build scripts are at https://github.com/rubocop-hq/circleci-ruby-snapshot-image.
The images are uploaded to https://hub.docker.com/r/rubocophq/ruby-snapshot/ and https://hub.docker.com/r/rubocophq/circleci-ruby-snapshot/ as `rubocophq/ruby-snapshot:latest` and `rubocophq/circleci-ruby-snapshot:latest`.

**Comment by Earlopain** [comment]
The above has stopped working for a few months now (https://github.com/rubocop/circleci-ruby-snapshot-image/issues/21) so I made my own thing at https://github.com/docker-ruby-nightly/ruby

The image variants mirror what is available over here and I'm also building for a few different platforms. It's hosted on the GitHub container registry so image tags look like `ghcr.io/docker-ruby-nightly/ruby:alpine3.20-nightly-2024-05-26` or `ghcr.io/docker-ruby-nightly/ruby:slim-bookworm-nightly`

**Comment by kachick** [comment]
How about using https://github.com/ruby/ruby-docker-images?

```console
> podman run -it rubylang/ruby:master-jammy
Resolving "rubylang/ruby" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/rubylang/ruby:master-jammy...
Getting image source signatures
Copying blob sha256:633c3a54b6f33f9c23e697bba5d1d82157cb60e42a8834d1f4fd1514798f27af
Copying blob sha256:af96b92b068e291633bde5c221d3ec3ddf11000faafff2881a8fbc94c4a5b5b3
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:a8b1c5f80c2d2a757adc963e3fe2dad0b4d229f83df3349fbb70e4d12dd48822
Copying blob sha256:6a3bb103e626aa8fd377c4061f233a441fce01b23252e6ba4d8e85275c213be4
Copying blob sha256:e3caad1d7ddce6549ec46b15adde0b041cc2c3aeb0a57dcef93c12be0df5fdaf
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:912f0da8e0888dac0c9da95d5c6a91b1561ae6e657d8a9923833f1972093a2f5
Copying blob sha256:6ec9f349c511b9f4f03341e5156c9e093c58227250dd7b0854bd5e5fe2045fcd
Copying blob sha256:4b55705af5ccc51f35449df6d7d8fd6aee6d9029c0905f23f733c54c21a0b499
Copying blob sha256:e928dfa53225e351517f296d4f8dac7be9c0746aa686dc4fe6d0f0a71d23aa0a
Copying blob sha256:85595551714108d3c6c3422ab9b5059153c6601b65dfd48bd5f53b62a1db5f9d
Copying blob sha256:3da85dab454d8319c60bec47f2992ef30507fd81410059a19bb9216ae633618f
Copying config sha256:f16dbe872ad67f8087cd7698b785bb0b1e7c36fb05eac5c0300988d4cbe477b9
Writing manifest to image destination
root@16845b4a2e8e:/# ruby -v
ruby 3.4.0dev (2024-05-27T09:16:28Z master bc47ca5546) [x86_64-linux]
```

**Comment by Earlopain** [comment]
Ruby doesn't officially support alpine/musl and I need these images so that doesn't work (for me at least). It might work better if you're already ubuntu-based but even then I would prefer something closer to how the images are build here.
