### ISSUE TITLE
Add buster images

### ISSUE THREAD

**Issue by dentarg** [docker-library/ruby#224]
Do you have any plans to add [buster](https://github.com/docker-library/buildpack-deps/tree/master/buster) images, or is it expected to be contributed by the community?

If someone would contribute, is it expected that images for all versions (2.3, 2.4, 2.5, 2.6) are added?

**Comment by tianon** [comment]
I'm sorry to say that I'm honestly pretty strongly -1 on adding `buster` variants right now.  Debian Buster is the current "testing" repository, which means that any package updates in Buster (including and especially security fixes) will be delayed anywhere from 2-10 days (and in some cases even longer).  Once Buster gets closer to freeze (and thus release as Stable), I'd be more willing to consider an additional variant for it.

**Comment by dentarg** [comment]
@tianon Thanks for the reply, when I opened the issue I didn't know that this was the case with buster (I thought it was stable as Ubuntu 18.04 LTS is based on it). I understand your hesitation to add `buster` today.

**Comment by tianon** [comment]
Sure!  See https://www.debian.org/releases/buster/ for more information about the Buster release. :+1:

**Comment by yosifkit** [comment]
Closing. Since we maintain the Debian images as well, we'll likely add Buster images once it is released later this year.
