### ISSUE TITLE
build 2.5.1 with Alpine 3.6 due to sidekick Segfaults

### ISSUE THREAD

**Issue by ashleyhull-versent** [docker-library/ruby#233]
Hello,

Mastodon is built with sidekick and we're recently committed from `ruby2.4.4-alpine3.6` to `ruby2.5.1-alpine3.7`... but have had to revert due to segfaults with sidekick.

We've planning to diagnose the root cause of these faults and would like to test with different version of alpine.

Thanks.

**Comment by ashleyhull-versent** [comment]
https://github.com/docker-library/ruby/pull/234

**Comment by ashleyhull-versent** [comment]
https://github.com/tootsuite/mastodon/pull/8712

**Comment by tianon** [comment]
Mirroring my comment from https://github.com/docker-library/ruby/pull/235:

> I'm not sure how I feel about adding a new variant based on Alpine 3.6 (especially as we're trying to move forward into Alpine 3.8 to replace 3.7 by default) -- I think the release last week (for the `apk` security fix) was more the exception than the norm, and that Alpine 3.6's ship has really sailed generally except for severe security vulnerabilities.
