### ISSUE TITLE
Ruby 2.3.8

### ISSUE THREAD

**Issue by brandysnaps** [docker-library/ruby#239]
Ruby 2.3.8 has been released:
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/

Is it possible to get an ETA of when the Dockerfiles will be updated with the new version?

**Comment by tianon** [comment]
As soon as https://doi-janky.infosiftr.net/job/update.sh/job/ruby/3052/console finishes doing a build test of it. :+1:

**Comment by chulkilee** [comment]
Ruby release blog post and ref in this repo:

- [Ruby 2.3.8 Released](https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/) - 36c87bb64362de2e6e9ea003104030ca2a5fc4e5
- [Ruby 2.4.5 Released](https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-4-5-released/) - 58cbeeb8ea937737eeb8f358472add230b6ded30
- [Ruby 2.5.2 Released](https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-5-2-released/) - eed4e6befb2d0b9d4735659315d825cf6e3bc02d
- [Ruby 2.5.3 Released](https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/) - #240

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/4972, which is currently getting a proper full build test and once merged will update tags on Docker Hub.
