### ISSUE TITLE
Ruby 2.3.8 stretch slim

### ISSUE THREAD

**Issue by captainkerk** [docker-library/ruby#243]
Hi,

Recently, the 2.3 Dockerfiles were updated to use 2.3.8, but the resulting image doesn't appear on dockerhub: https://github.com/docker-library/ruby/commit/36c87bb64362de2e6e9ea003104030ca2a5fc4e5#diff-5203455a94919a14082cdb13d8ad046cL22

Could you push the 2.3.8 tagged images to dockerhub?

Thanks!

**Comment by tianon** [comment]
https://github.com/docker-library/ruby#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet + https://github.com/docker-library/official-images/pull/4972 (it's in-flight) :+1:

**Comment by captainkerk** [comment]
Gotcha, thanks for the quick response.
