### ISSUE TITLE
BUNDLER_VERSION env variable will afffect how bundler works in the future

### ISSUE THREAD

**Issue by deivid-rodriguez** [docker-library/ruby#246]
The official docker images set several environment variables that as far as I know only affect building the image. It has been proposed in the past to move these environment variables to `ARG`s, but it was [rejected](https://github.com/docker-library/ruby/pull/112#issuecomment-421143450).

The future behavior of bundler will be that it will automatically exec to the bundler version the lock file was generated with (the `BUNDLED_WITH` section in the lock file). This default behavior will be overridable with an environment variable called `BUNDLER_VERSION`.

The problem is that since the ruby docker images set the `BUNDLER_VERSION`, that will change the default behavior of `bundler` to ignore the version locked in the lock file. As bundler maintainers, we think this will cause confusion and will inhibit this new feature that we consider interesting to end users.

So, I would like to request that this environment variable is moved to an `ARG`, or at least renamed.

See https://github.com/bundler/bundler/issues/6782 for more.

Thanks!

**Comment by yosifkit** [comment]
A rename of the variable seems sane to me. Not sure what it should be. Any suggestions that will be unlikely to be used by bundler?

To go a little further, what if we also stop including a specific version of bundler and rubygems and instead rely on the version packaged with ruby?  I think we could do so by pinning to the current versions (1.17.3 and 3.0.1) and then dropping the update code in the Dockerfile when a newer ruby release catches up. This would stop us from breaking users so often, but would make them responsible for updating bundler/rubygmes in their own Dockerfile if they want a newer version.

**Comment by deivid-rodriguez** [comment]
My preferred solution would be to remove the environment variable, but if that's not possible, maybe `DEFAULT_BUNDLER_VERSION`?

Regarding no longer including a specific version of bundler and rubygems, I like the idea! :+1:

**Comment by tianon** [comment]
See https://github.com/docker-library/ruby/pull/255 (and please feel free to share it around to other Rubygems and/or Bundler maintainers in case there's something we've missed that makes it continue to make sense for us to update either of these things). :+1: :heart:

**Comment by deivid-rodriguez** [comment]
Thanks @tianon! I agree with the approach but I also agree with making sure the rest of the bundler & rubygems team is aware of this and shares any concerns they may have.

I shared this discussion and proposal around, so hopefully we'll hear some thoughts from others :+1:
