### ISSUE TITLE
ETA on official Ruby 2.6.0 image?

### ISSUE THREAD

**Issue by jdickey** [docker-library/ruby#254]
It Would Be Very Nice If™ a proper 2.6.0 release could happen soon (with updated Bundler and RubyGems). Is there any estimated schedule for this so those of us downstream can plan our own migration/upgrade strategy?

Thanks for all the work!

**Comment by mikegee** [comment]
Looks like this PR needs merged: https://github.com/docker-library/official-images/pull/5234

**Comment by tianon** [comment]
Which is now done -- the official build servers should pick it up shortly. :+1:

**Comment by jdickey** [comment]
Great; thanks! I missed that; sorry...
