### ISSUE TITLE
"Slim" Dockerfile not actually using "stretch-slim" version of Debian image

### ISSUE THREAD

**Issue by jamescontent** [docker-library/ruby#256]
If you check out the debian slim [Dockerfile](https://github.com/docker-library/ruby/blob/master/2.6/stretch/slim/Dockerfile), specifically line 1 -> `FROM debian:stretch`, it's not actually using the Debian slim build. I've made the change locally and rebuilt. As shown below, it does build correctly and a naive smoke check came back positive.

<img width="627" alt="screen shot 2019-01-03 at 7 25 01 am" src="https://user-images.githubusercontent.com/7839509/50637641-ca616600-0f28-11e9-8e3a-126e678ef7a4.png">
<img width="620" alt="screen shot 2019-01-03 at 7 25 22 am" src="https://user-images.githubusercontent.com/7839509/50637643-cf261a00-0f28-11e9-95ae-d6153effda8f.png">
<img width="629" alt="screen shot 2019-01-03 at 7 26 37 am" src="https://user-images.githubusercontent.com/7839509/50637676-ef55d900-0f28-11e9-9204-abefae0290d7.png">

Was there a reason that the "slim" debian build doesn't actually use the slim debian image? I realize it's not a ton of space saved, but I would personally appreciate those 42 mb for a project I'm currently working on.

Happy to put a PR together if there isn't some reason to stay on "fat" debian stretch.

PS: my apologies if this doesn't conform to an issue (or PR) standard, I couldn't find any guidelines.

**Comment by yosifkit** [comment]
We made the `slim` images in `ruby` before we had made the Debian slim images, so this sounds like a good change to me (and hopefully won't break anyone).

**Comment by tianon** [comment]
PR opened: https://github.com/docker-library/ruby/pull/257

(That'll run the couple explicit tests we've got, which should help us verify this somewhat.)

**Comment by jamescontent** [comment]
@yosifkit @tianon Thanks!

**Comment by bhaveshf-cuelogic** [comment]
in our current Dockerfile below was the sequcne of commands which seems to be breaking now:

```
FROM ruby:2.4-slim
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client curl nodejs yarn ca-certificates
```

This was working till yesterday as follows:
```
10:57:19: Setting up postgresql-client-9.6 (9.6.10-0+deb9u1) ...
10:57:19: update-alternatives: using /usr/share/postgresql/9.6/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
10:57:19: Setting up g++ (4:6.3.0-4) ...
10:57:19: update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
10:57:19: Setting up postgresql-client (9.6+181+deb9u2) ...
10:57:19: Setting up build-essential (12.3) ...
10:57:19: Setting up dh-python (2.20170125) ...
10:57:21: Setting up python3 (3.5.3-1) ...
10:57:21: running python rtupdate hooks for python3
```

but from today we are getting following error related to postgres9.6

```09:55:01: Setting up postgresql-client-9.6 (9.6.10-0+deb9u1) ...
09:55:01: update-alternatives: using /usr/share/postgresql/9.6/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
09:55:01: update-alternatives: error: error creating symbolic link '/usr/share/man/man1/psql.1.gz.dpkg-tmp': No such file or directory
09:55:01: dpkg: error processing package postgresql-client-9.6 (--configure):
09:55:01: subprocess installed post-installation script returned error exit status 2
09:55:01: Setting up g++ (4:6.3.0-4) ...
09:55:01: update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
09:55:01: dpkg: dependency problems prevent configuration of postgresql-client:
09:55:01: postgresql-client depends on postgresql-client-9.6; however:
09:55:01: Package postgresql-client-9.6 is not configured yet.
09:55:01: dpkg: error processing package postgresql-client (--configure):
09:55:01: dependency problems - leaving unconfigured
09:55:01: Setting up build-essential (12.3) ...
09:55:01: Setting up dh-python (2.20170125) ...
09:55:05: Setting up python3 (3.5.3-1) ...
09:55:05: running python rtupdate hooks for python3.5...
09:55:05: running python post-rtupdate hooks for python3.5...
09:55:05: Setting up lsb-release (9.20161125) ...
09:55:05: Processing triggers for libc-bin (2.24-11+deb9u3) ...
09:55:05: Errors were encountered while processing:
09:55:05: postgresql-client-9.6
09:55:05: postgresql-client
09:55:05: [91mE: Sub-process /usr/bin/dpkg returned an error code (1)
```

Can anyone look into this and suggest what changes needs to be done ?

**Comment by jamescontent** [comment]
Would it be possible to post a redacted version of the entire dockerfile?

**Comment by bhaveshf-cuelogic** [comment]
Here it is

```
FROM ruby:2.4-slim
EXPOSE 3000
RUN apt-get update -qq && apt-get install -y apt-transport-https gpg

# add yarn and node sources
ADD https://dl.yarnpkg.com/debian/pubkey.gpg /tmp/yarn-pubkey.gpg
RUN apt-key add /tmp/yarn-pubkey.gpg && rm /tmp/yarn-pubkey.gpg
RUN echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list
ADD https://deb.nodesource.com/gpgkey/nodesource.gpg.key /tmp/nodekey.gpg
RUN apt-key add /tmp/nodekey.gpg && rm /tmp/nodekey.gpg
RUN echo 'deb https://deb.nodesource.com/node_8.x jessie main' > /etc/apt/sources.list.d/node.list

# updte and install
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev postgresql-client curl nodejs yarn ca-certificates
# following libraries are needed as dependency for pdfkit gem
RUN apt-get install -y libxrender1 libfontconfig1 libxext6

RUN mkdir /app
WORKDIR /app

# install gem deps and yarn deps
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
COPY yarn.lock yarn.lock
RUN gem install bundler
RUN bundle install --binstubs

COPY . .
COPY --from=envcrypt-build /go/bin/envcrypt bin/envcrypt

# precompile the assets
RUN yarn install
RUN bundle exec rake assets:precompile

CMD ["sh", "deploy/entrypoint.sh"]
```

**Comment by jamescontent** [comment]
Thanks! I did some digging and it looks like the slim debian isn't including a few dirs out of the box now. If you update the line in question to have these new directives it should work. At least, when I created a Dockerfile it worked for me.

```
FROM ruby:2.4-slim
RUN apt-get update -qq && mkdir -p /usr/share/man/man1 && mkdir -p /usr/share/man/man7 && apt-get install -y build-essential libpq-dev postgresql-client curl nodejs yarn ca-certificates
CMD ["sh"]
```

Notice the `mkdir` directive. I came across in this gist / posts -> 
https://github.com/dalibo/temboard/issues/211
https://github.com/debuerreotype/debuerreotype/blob/master/scripts/.slimify-excludes
https://github.com/dalibo/temboard/commit/ff98d6740ae11345658508b02052294d6cffd448
