### ISSUE TITLE
The base image is huge

### ISSUE THREAD

**Issue by elliotlarson** [docker-library/ruby#264]
The image size for the base Ruby image seems crazy big.

```text
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ruby                2.6                 ae96a4ad4f3f        9 days ago          868MB
```

I'm new to Docker, so I'm sure I'm misunderstanding something, but why is the image almost a gigbyte?

The Alpine ruby image seems reasonably sized:

```text
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ruby                2.6-alpine          708614d8fa07        13 days ago         47.4MB
```

I'd expect the base image to be bigger than an Alpine version, but not almost 20 times as big.

**Comment by wglambert** [comment]
You'd might like `ruby:slim` then
```console
$ docker images | grep ruby
ruby                          2.6                  ae96a4ad4f3f        9 days ago          868MB
ruby                          2.6-slim             97103f1fba67        9 days ago          126MB
ruby                          2.6-alpine           708614d8fa07        13 days ago         47.4MB
```
The `ruby` images come in many flavors, each designed for a specific use case.
https://github.com/docker-library/docs/tree/master/ruby#image-variants


```console
$ docker history ruby:2.6
IMAGE               CREATED             CREATED BY                                      SIZE
. . .          
<missing>           9 days ago          /bin/sh -c set -ex;  apt-get update;  apt-ge…   560MB
<missing>           9 days ago          /bin/sh -c apt-get update && apt-get install…   142MB
<missing>           9 days ago          /bin/sh -c set -ex;  if ! command -v gpg > /…   7.81MB
<missing>           9 days ago          /bin/sh -c apt-get update && apt-get install…   23.2MB
<missing>           9 days ago          /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           9 days ago          /bin/sh -c #(nop) ADD file:4fec879fdca802d69…   101MB

$ docker history ruby:2.6-slim
IMAGE               CREATED             CREATED BY                                      SIZE
. . .               
<missing>           9 days ago          /bin/sh -c set -ex   && buildDeps='   autoco…   35.9MB
. . .                           
<missing>           9 days ago          /bin/sh -c apt-get update  && apt-get instal…   34.5MB
<missing>           9 days ago          /bin/sh -c #(nop)  CMD ["bash"]                 0B 
<missing>           9 days ago          /bin/sh -c #(nop) ADD file:5a6d066ba71fb0a47…   55.3MB

$ docker history ruby:2.6-alpine
IMAGE               CREATED             CREATED BY                                      SIZE 
. . .              
<missing>           13 days ago         /bin/sh -c set -ex   && apk add --no-cache -…   41.8MB
. . .             
<missing>           13 days ago         /bin/sh -c mkdir -p /usr/local/etc  && {   e…   45B
<missing>           2 weeks ago         /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B
<missing>           2 weeks ago         /bin/sh -c #(nop) ADD file:2a1fc9351afe35698…   5.53MB
```

**Comment by elliotlarson** [comment]
@wglambert Thanks for showing me the `history` command!  That definitely helps me see where the extra size is coming from.  Also, thank you for the link to the docs that talk about the image variants.  That was helpful too.

The docs sort of lead to using the base image.  The last comment in the slim section is: 

> ... we highly recommend using the default image of this repository

Since I'm a noob, the base image appeals to me.  I'd like to get up and running with an image that represents the most common use case, or the most well worn path.  However, the image seems almost unworkably large.  I mean, it's not an issue when I'm using Docker just for development.  I don't really mind the size on my local machine.  But if I'm deploying Docker images for a production app, the almost 1 gigabyte size gives me pause.

I guess I have two concerns about the size: 1) the amount of time it takes to push and pull from a registry for both CI and deployment; 2) the amount of space this could potentially take up on a VPS where disk space is more limited.

Maybe the desire to handle as many use cases as possible with the base image just means it's going to be huge.  But I figure it's worth discussing.  Can some of the general use cases be sacrificed in an effort to get the size in a more reasonable range?

**Comment by wglambert** [comment]
The base image is geared for development, such that you just do a `FROM: ruby` and your app should just work as it comes with the most common software packages.

But for deploying you could opt for the slim or alpine variants and then add your dependencies if you have space constraints. Since they just come with ruby without the additional software packages, so you have a minimal base to add just what's necessary for the app you're deploying.

**Comment by elliotlarson** [comment]
@wglambert Okay, I see.  I feel like one of the touted benefits of Docker is that you run the same environment/image in development, CI, and production.  But, it sounds like the base image isn't a good fit for production apps.  If that's by design, I think it would help to have information in the README about how the base image is only intended for development work.

**Comment by yosifkit** [comment]
As for running the same image everywhere, once you have the list of OS packages that you need, then using that "prod" Dockerfile with `FROM ruby:2.6-slim` for development should be fine. Updating the Dockerfile when you need new OS libraries for new gems.

> the base image is only really intended for development work.

Well, that depends. If an organization has many different ruby services, each with their own dependencies, then the large base image could actually save them from duplicating OS packages across multiple ruby based images. Plus you really only pay the base image download tax when you update it; so if you use the `sha256` hash of the image ([`FROM ruby@sha256:2f936113d9e8fc7a349577a8fa75bd9a955267d2a1fc9cf793b2f1d4fab73636`](https://github.com/docker-library/repo-info/blob/86649a8d065618fc520da21215b0b0a89e0dcf46/repos/ruby/remote/2.6.md#ruby26---linux-amd64) for the current `ruby:2.6` on amd64), it will only change when you update it (this could get you closer to a reproducible build :wink:).

**Comment by elliotlarson** [comment]
@yosifkit Thank you for the tip on using the SHA hash of the image.  I'll give that a try.
