### ISSUE TITLE
Error due to missing libgmp when installing nokogiri gem on ruby:2.5-slim

### ISSUE THREAD

**Issue by abevoelker** [docker-library/ruby#267]
Moving [from discussion](https://github.com/docker-library/ruby/commit/eae22dc2dfe30b48f1633912396110539e1b8d49#commitcomment-32559528) on eae22dc2dfe30b48f1633912396110539e1b8d49. It seems that libgmp is somehow missing on the latest `ruby:2.5-slim` image. Others reported similar behavior on the alpine image.

```
$ docker pull ruby:2.5-slim
2.5-slim: Pulling from library/ruby
Digest: sha256:c8d66ac4a1fa252df07f505f9dc02b5ee203f33b66406bfddca5c55c1d5f4b58
Status: Image is up to date for ruby:2.5-slim

$ docker run -it --rm ruby:2.5-slim /bin/bash
root@6465f040df18:/# apt-get update >/dev/null 2>&1
root@6465f040df18:/# apt-get -y install -qq -o=Dpkg::Use-Pty=0 build-essential libxslt-dev libxml2-dev >/dev/null 2>&1
root@6465f040df18:/# gem install nokogiri
Fetching nokogiri-1.10.1.gem
Fetching mini_portile2-2.4.0.gem
Successfully installed mini_portile2-2.4.0
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/nokogiri-1.10.1/ext/nokogiri
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.5.0 -r ./siteconf20190303-931-p72cjl.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/usr/local/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
        from /usr/local/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
        from /usr/local/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /usr/local/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:416:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/bundle/extensions/x86_64-linux/2.5.0/nokogiri-1.10.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/nokogiri-1.10.1 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.5.0/nokogiri-1.10.1/gem_make.out


root@6465f040df18:/# cat /usr/local/bundle/extensions/x86_64-linux/2.5.0/nokogiri-1.10.1/mkmf.log
"gcc -o conftest -I/usr/local/include/ruby-2.5.0/x86_64-linux -I/usr/local/include/ruby-2.5.0/ruby/backward -I/usr/local/include/ruby-2.5.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wduplicated-cond -Wno-maybe-uninitialized  -fPIC  conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby  -lpthread -lgmp -ldl -lcrypt -lm   -lc "
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

It seems that `libgmp-dev` somehow didn't make it into the image, because I can manually install it and then things work okay:

```
root@6465f040df18:/# apt-get install libgmp-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgmpxx4ldbl
Suggested packages:
  gmp-doc libgmp10-doc libmpfr-dev
The following NEW packages will be installed:
  libgmp-dev libgmpxx4ldbl
0 upgraded, 2 newly installed, 0 to remove and 10 not upgraded.
Need to get 653 kB of archives.
After this operation, 1971 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://deb.debian.org/debian stretch/main amd64 libgmpxx4ldbl amd64 2:6.1.2+dfsg-1 [22.2 kB]
Get:2 http://deb.debian.org/debian stretch/main amd64 libgmp-dev amd64 2:6.1.2+dfsg-1 [631 kB]
Fetched 653 kB in 0s (2493 kB/s)    
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libgmpxx4ldbl:amd64.
(Reading database ... 13068 files and directories currently installed.)
Preparing to unpack .../libgmpxx4ldbl_2%3a6.1.2+dfsg-1_amd64.deb ...
Unpacking libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-1) ...
Selecting previously unselected package libgmp-dev:amd64.
Preparing to unpack .../libgmp-dev_2%3a6.1.2+dfsg-1_amd64.deb ...
Unpacking libgmp-dev:amd64 (2:6.1.2+dfsg-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Setting up libgmpxx4ldbl:amd64 (2:6.1.2+dfsg-1) ...
Setting up libgmp-dev:amd64 (2:6.1.2+dfsg-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...

root@6465f040df18:/# gem install nokogiri
Building native extensions. This could take a while...
Successfully installed nokogiri-1.10.1
1 gem installed
```

Alternatively, installing `libgmp3-dev` also works to fix the issue.

**Comment by dentarg** [comment]
Looks like `libgmp-dev` is not just a build dependency, but needs to be present at runtime too, if Ruby was built with it. See https://github.com/rvm/rvm/issues/3509, https://github.com/travis-ci/travis-rubies/issues/15, https://github.com/travis-ci/travis-rubies/pull/16

Maybe slim variants should not be built with `libgmp-dev`?

**Comment by NikoRoberts** [comment]
@abevoelker
> It seems that libgmp-dev somehow didn't make it into the image

This is because it is added to the `build-deps` it gets cleaned up by the `apt-get purge -y --auto-remove $buildDeps`

Similar behaviour now with Alpine. You need to `apk add --no-cache gmp-dev` on your Dockerfile so Nokogiri gem can install native extensions.

We haven't found exactly what was happening previously. My hunch is that gmp-dev was installed already but wasn't getting removed/purged

**Comment by dentarg** [comment]
> We haven't found exactly what was happening previously. My hunch is that gmp-dev was installed already but wasn't getting removed/purged

Previously, there was no gmp library present at all (build or runtime), for any image variant. #266 and docker-library/buildpack-deps#92 introduced the gmp libraries, but only as a build dependencies. It sure looks like the gmp library need to be present at runtime, if Ruby was built with it. Ping @tianon

**Comment by tianon** [comment]
Whoops, yep, looks like we need to keep `libgmp-dev` / `gmp-dev` installed in `slim` / `alpine` too.

**Comment by mirth** [comment]
Same thing was for mongoid gem. Wrote it so it could be indexed by google.

**Comment by tianon** [comment]
This will happen for _any_ native extension (no need to list them all here).  I've filed https://github.com/docker-library/ruby/pull/269 to hopefully get this fixed swiftly.

**Comment by NobodysNightmare** [comment]
Meta-question regarding this: Could I have avoided running into this, by using a more specific version tag?

We were assuming to have a repeatable build, but we used the version tag 
`ruby:2.5.3-alpine`. Apparently it is very expected for this version tag to still receive updates, which breaks any assumption about repeatable builds.

Could I have specified a version, that would not have received any further updates? Basically I am looking for a mechanism that brings me as closely as possible to a `Gemfile.lock`, just for my base image...

**Comment by juusujanar** [comment]
@NobodysNightmare You can specify image SHA instead of a version tag. This will lock to very specific image.

**Comment by tareksamni** [comment]
@NobodysNightmare if you do not want/care to receive updates for a specific `image:tag` .. then cache (pull + push) it to your own docker repo and use that. By using the docker-library you opt-in for all the updates/patches that come to an image even though you specify a tag. A tag guarantees you specific software (ruby/os in this case) version lock but not the same image (it might get new updates every now and then)!

**Comment by NobodysNightmare** [comment]
Okay, thanks for your replies. So I hear, that the best-practice is, that I keep track of that myself :)

Considering, that we have multiple downstream applications depending on the same image, I will probably not use a private registry to cache the images, since I would still need to tag images in a meaningful way (which I probably can't do in a good/automated way).

We might extend our tooling around managing docker setup to set the SHA instead of the tag in the `Dockerfile` and then add a `bundle update`-style way to update that SHA to the latest version.

**Comment by tareksamni** [comment]
You can:
Option 1 (what you are doing now):
- Nice image tag (meaningful not just SHA).
- Continuously get all updates/patches.

Option 2 (Use SHA):
- Bad image tags (not meaningful and hard to track changes).
- Lock your image (no more updates/patches).

Option 3 (Host/Cache the image to your own docker repo):
- Nice image tag (meaningful not just SHA).
- Lock your image (no more updates/patches).

You choose and consider what would be the best practice for you! If you are saying, that you specifically want to lock the image and not get the updates/patches. I can not see why the third option is not a viable good practice.

**Comment by morgoth** [comment]
@abevoelker Got the same error on `ruby:2.6.1-slim-stretch`
I'm installing `libgmp-dev` by hand, but I still get this error. Do you now what could be wrong?

**Comment by abevoelker** [comment]
@morgoth not sure, sorry
