### ISSUE TITLE
Ruby 2.6.2

### ISSUE THREAD

**Issue by foxeg** [docker-library/ruby#273]
Ruby got updated to 2.6.2 with security updated
There are changes in library though still getting

> manifest for ruby:2.6.2-alpine not found

**Comment by cabello** [comment]
2.5.4 as well, we heard from the maintainer that this process is currently not automated, so it takes a little bit longer.

**Comment by tianon** [comment]
Yep, needs another PR before it can go up.

To be clear though, there's no security bump for us in this version bump because we already bumped RubyGems in a previous upload (and that's where the security issue is).

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/5542 :+1:
