### ISSUE TITLE
Upgrade to Ruby 2.5.5

### ISSUE THREAD

**Issue by patch0** [docker-library/ruby#274]
This [was released today](https://www.ruby-lang.org/en/news/2019/03/15/ruby-2-5-5-released/), and fixes an issue with multi-threaded multi-process app (eg. puma).

**Comment by wglambert** [comment]
We have a bot that applies these updates automatically
See https://github.com/docker-library/ruby/commit/6f3497e40d44651802e1ec8a4647b23a3a63b355

This will be pushed to Dockerhub later on https://github.com/docker-library/ruby#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

**Comment by patch0** [comment]
Sorry-- I did look before opening the request.  I think I must have looked in the wrong place :)

Thanks!

**Comment by gucki** [comment]
@wglambert Sadly there's still no docker image for 2.5.5. I'm sorry, but after looking at https://github.com/docker-library/ruby#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet, I still don't get how the build/ release is actually triggered. Could the docs for this be improved? Could it be triggered manually too?

**Comment by dentarg** [comment]
[docker-library/official-images](https://github.com/docker-library/official-images) seems to need manual updates, this was the PR for 2.6.2 and 2.5.4: https://github.com/docker-library/official-images/pull/5542

**Comment by gucki** [comment]
@dentarg How can I create a PR to get https://github.com/docker-library/ruby/commit/6f3497e40d44651802e1ec8a4647b23a3a63b355 merged? :)

**Comment by gucki** [comment]
BTW, the comments in https://github.com/docker-library/ruby/issues/263 give a bit more insight on how the process works. @yosifkit Could you please create a PR for it? That'd be awesome.
