### ISSUE TITLE
Wheezy and Jessie were recently removed from the apt mirror network - broken image

### ISSUE THREAD

**Issue by innovia** [docker-library/ruby#275]
Wheezy and Jessie have been integrated into the archive.debian.org
structure recently, we are now removing all of Wheezy and all non-LTS
architectures of Jessie from the mirror network starting today.

apt-get update now breaks with 404 errors rendering CI systems inoperable

as I can switch to debain9-stretch, I think this is a major issue that can be resolved using the workaround below and committed to your latest tags for debain 8-jessie and 7-wheezy

https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository?newreg=6d7d6f25b1684950b68763d35a68d55b

https://unix.stackexchange.com/questions/2544/how-to-work-around-release-file-expired-problem-on-a-local-mirror

**Comment by tianon** [comment]
Regarding Jessie, see https://github.com/debuerreotype/docker-debian-artifacts/issues/66#issuecomment-476648047.

Regarding Wheezy, we don't have any images based on Debian Wheezy in Ruby. :+1:
