### ISSUE TITLE
Upgrade to Ruby 2.4.6

### ISSUE THREAD

**Issue by paveg** [docker-library/ruby#277]
This [was released yesterday](https://www.ruby-lang.org/en/news/2019/04/01/ruby-2-4-6-released/) .

**Comment by tianon** [comment]
Fixed `update.sh` bug in 5dc3cbb that caused this to get missed and manually triggered https://doi-janky.infosiftr.net/job/update.sh/job/ruby/ which should do the update, test, and prep a PR branch to https://github.com/docker-library/official-images for us. :+1:
