### ISSUE TITLE
Bundle install --deployment doesn't work

### ISSUE THREAD

**Issue by orien** [docker-library/ruby#288]
Using the `--deployment` flag when running `bundle install` fails in the latest Ruby images.

Steps to reproduce:

1. Save the following files:

   Dockerfile
   ```dockerfile
   FROM ruby:alpine
   COPY Gemfile Gemfile.lock ./
   RUN bundle install --deployment
   ```

   Gemfile
   ```ruby
   source "https://rubygems.org"
   ```

   Gemfile.lock
   ```Gemfile.lock
   GEM
     remote: https://rubygems.org/
     specs:

   PLATFORMS
     ruby

   DEPENDENCIES
   
   BUNDLED WITH
      1.7.3
   ```

1. Build the Docker image:

   ```sh
   docker build .
   ```

Expected result: the image is built successfully.

Actual result: the image fails to build with the following output:

```
Sending build context to Docker daemon  6.656kB
Step 1/3 : FROM ruby:alpine
 ---> 98fcf3490b83
Step 2/3 : COPY Gemfile Gemfile.lock ./
 ---> Using cache
 ---> 83a8d319f2ae
Step 3/3 : RUN bundle install --deployment
 ---> Running in effdc6055e52
Using a custom path while using system gems is unsupported.

path:
Set for your local app (/usr/local/bundle/config): "vendor/bundle"

path.system:
Set via BUNDLE_PATH__SYSTEM: true

disable_shared_gems:
You have not configured a value for `disable_shared_gems`
The command '/bin/sh -c bundle install --deployment' returned a non-zero code: 15
```

This seems related to #285.

**Comment by orien** [comment]
Similarly, using the `--path` option causes the same error.

**Comment by Jack12816** [comment]
FYI @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
Yes, this is clearly related. I'm going to have a look right now.

**Comment by MarcelEeken** [comment]
This is possibly introduced with this change https://github.com/docker-library/ruby/blob/e040029c82501556371e9d84a9db607dfb1bba51/2.6/stretch/Dockerfile

**Comment by akirakoyasu** [comment]
Workaround: specifying `--frozen` option is ok?

**Comment by deivid-rodriguez** [comment]
I think this is a bug in `bundle install --deployment`, but it needs to be discussed carefully and even if fixed, it will take time to propagate, so I think we should revert my changes. I'll open a PR, sorry for the trouble :(

**Comment by Jack12816** [comment]
> Workaround: specifying `--frozen` option is ok?

@akirakoyasu Unfortunately no, some builds rely on the `vendor/bundle` path (or the given `--path`) for say smoke tests, dependency compression, etc.

**Comment by akirakoyasu** [comment]
@Jack12816 
Thanks!

**Comment by deivid-rodriguez** [comment]
Proposed the revert in #289.

**Comment by Jack12816** [comment]
Thank you @deivid-rodriguez :+1:

**Comment by mafonso** [comment]
I had a case where `bundle install --clean  --without "development"` was failing with same "error 15", and adding `--force` fixed it.

**Comment by mediafinger** [comment]
Yes, same issue here for multiple apps:

```
$ bundle check --path vendor/bundle || bundle install --without production --jobs $(nproc) --path vendor/bundle --binstubs vendor/bundle/bin
Using a custom path while using system gems is unsupported.

path:
Set for your local app (/usr/local/bundle/config): "vendor/bundle"

path.system:
Set via BUNDLE_PATH__SYSTEM: true

disable_shared_gems:
You have not configured a value for `disable_shared_gems`
Using a custom path while using system gems is unsupported.

path:
Set for your local app (/usr/local/bundle/config): "vendor/bundle"

path.system:
Set via BUNDLE_PATH__SYSTEM: true

disable_shared_gems:
You have not configured a value for `disable_shared_gems`
```

Hope the `Open` label changes to `Merged` soon :wink:
