### ISSUE TITLE
Images for Ruby 2.6.4 and 2.5.6 (and presumably 2.4.7) not accessible

### ISSUE THREAD

**Issue by jdickey** [docker-library/ruby#295]
Issue #294 having been closed and the [Docker Hub landing page](https://hub.docker.com/_/ruby) updated, I would expect to be able to pull (e.g.) `ruby:2.6.4-stretch` and `ruby:2.5.6-stretch` from Docker Hub.

However,

```
$ docker image pull ruby:2.6.4-stretch          
Error response from daemon: manifest for ruby:2.6.4-stretch not found: manifest unknown: manifest unknown
$ docker image pull ruby:2.5.6-stretch
Error response from daemon: manifest for ruby:2.5.6-stretch not found: manifest unknown: manifest unknown
$ docker image pull ruby:2.6-stretch  
2.6-stretch: Pulling from library/ruby
9cc2ad81d40d: Pull complete 
e6cb98e32a52: Pull complete 
ae1b8d879bad: Pull complete 
42cfa3699b05: Pull complete 
053cac798c4e: Pull complete 
66c0da710709: Pull complete 
c43743eb5f9a: Pull complete 
9a5f5de6bfcd: Pull complete 
Digest: sha256:25090bba1792428e72a37a25e2f1fdc544d4bebe2cc0340d300c5b8036d55e91
Status: Downloaded newer image for ruby:2.6-stretch
docker.io/library/ruby:2.6-stretch
$ docker run -it --rm ruby:2.6-stretch ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
$
```

Did someone forget to feed the gerbils?

Docker version 19.03.1, build 74b1e89 (running as Docker Desktop for Mac)

**Comment by 1gn0r4nd** [comment]
Hi,
Came here to ask the same thing.
The description indicates: 2.6.4-alpine3.10, 2.6.4-alpine3.9, but I can't find either in the tags.
I'm guessing the images just didn't get build

**Comment by CodingAnarchy** [comment]
I'm getting the same issue with `ruby:2.6.4-alpine`. Looks like the images weren't built, or weren't pushed up if they were.

**Comment by jdickey** [comment]
You'd think that they wouldn't update the README until *after* they'd successfully pushed the images, but I guess I'm just too old-school.

**Comment by tianon** [comment]
There was a glitch in the build infrastructure that caused our manifest list updates to fail; I've fixed it this morning and the builds should be up.
