### ISSUE TITLE
Setting BUNDLE_PATH is not a feature!

### ISSUE THREAD

**Issue by kwerle** [docker-library/ruby#297]
```
➜  ~ docker run --rm ruby:2.5.7 bash -c 'echo $BUNDLE_PATH'
/usr/local/bundle
```

Having the environment variable BUNDLE_PATH being set is a surprise.  I didn't set it, and bundler uses the environment variable over the file configuration.  Bundler has a default if it's not set.

I don't think the ruby container should set this environment variable.

**Comment by wglambert** [comment]
Looks like it was an upstream recommendation
https://github.com/docker-library/ruby/blob/924602dc917e27f8af6b35f838d11e7f3f39b2dc/2.6/buster/Dockerfile#L82-L85

https://github.com/docker-library/ruby/pull/208

**Comment by kwerle** [comment]
I don't see a call for it, and it really is painful.  I don't expect anyone but me to set environment variables unless they are specifically required by the software in a container - and it just isn't.
In addition, there is no good way to unset an environment variable in a child container.  You pretty much need to resort to
```
RUN unset BUNDLE_PATH
```
which I would describe as a workaround.  Everyone who sets BUNDLE_PATH in their .bundle/config file is going to see it break with this change.

**Comment by kwerle** [comment]
And even `RUN unset BUNDLE_PATH` is not sufficient.  This really is a breaking change.

**Comment by yosifkit** [comment]
The `BUNDLE_PATH` was added in https://github.com/docker-library/ruby/pull/69. At this point, I don't think we could roll that back without breaking users.  Can't you work around in by setting the value to be empty?

```console
$ docker run -it --rm -e BUNDLE_PATH= ruby env
PATH=/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=37ca18bf911d
TERM=xterm
BUNDLE_PATH=
RUBY_MAJOR=2.6
RUBY_VERSION=2.6.5
RUBY_DOWNLOAD_SHA256=d5d6da717fd48524596f9b78ac5a2eeb9691753da5c06923a6c31190abe01a62
GEM_HOME=/usr/local/bundle
BUNDLE_SILENCE_ROOT_WARNING=1
BUNDLE_APP_CONFIG=/usr/local/bundle
HOME=/root
```

**Comment by kwerle** [comment]
I have just realized that the real root of the poison is 
```
BUNDLE_APP_CONFIG=/usr/local/bundle
```

What that is saying is that your app is located in /usr/local/bundle instead of '.'.
*That* is why changes to ./.bundle/config are failing.

It looks like that was done at the same time.  Fortunately, I can set that correctly for my app and that should do the trick.  But it seems like it was a horrible idea!

**Comment by yosifkit** [comment]
That was done to facilitate a user that mounts their working directory into a ruby container so that they can live edit and not have to rebuild their image.  This would either mask the installs done in the image via `bundle install` or very often the local directory already had a `.bundle` directory that contains stuff for their host (like darwin) that would be incompatible with the container.

**Comment by kwerle** [comment]
Ugh.  I don't like it, but I can work around it.  It would have been *much* nicer to do all the default config settings in ~/.bundle/config and leave environment variables out of it.  Much easier to tweak files than env vars.
