### ISSUE TITLE
missing sync.rb

### ISSUE THREAD

**Issue by hadmut** [docker-library/ruby#304]
Hi,

I experienced the problem that a docker-image based on ruby:alpine (running a puppet master) was working last week, but can't be built now. 

Reason: ruby:alpine is now based on ruby 2.7, and the file sync.rb is missing. 

2.6-alpine:
/usr/local/lib/ruby/2.6.0/sync.rb exists. 

2.7-alpine:
no such file in /usr/local/lib/ruby/2.7.0

That's why puppet aborts with error message during runtime. 

I'm not sure whether this is a bug of the docker image or a regression/incompatibility in ruby itself. Please check.  
regards

**Comment by dentarg** [comment]
"Synchronizer (sync gem)" is no longer bundled with Ruby, see https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/. You need to install it yourself.

**Comment by tianon** [comment]
Good catch, thanks @dentarg :+1:
