### ISSUE TITLE
Tags updated daily??

### ISSUE THREAD

**Issue by mltsy** [docker-library/ruby#307]
I'm wondering what is the expected frequency of updates for a tag like 2.5.7.  I'm not too familiar with the process that is used to maintain the docker image repo for this project, but it seems like the 2.5.7 tag is being updated very frequently (daily?), even though the last time there was an update to the code here was a month ago.  I *think* this is what is causing my images to be built from scratch rather than using cached layers (which is what I'm trying to optimize, currently).

Is it true that these images are updated daily for some reason, or am I mistaken?  If it is true, is there some way to avoid the daily pushes that don't seem to be updating anything consequential?

**Comment by wglambert** [comment]
We have a faq entry on how an image is updated https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what

If you use a specific tag like `ruby:2.7.0-buster` you will only get updates for that version, as opposed to `ruby:latest` where you'll get version bumped

These are the only updates that get pushed to Dockerhub https://github.com/docker-library/official-images/pulls?q=is%3Apr+ruby+is%3Aclosed+label%3Alibrary%2Fruby
Last one was 28 days ago

**Comment by mltsy** [comment]
Okay, so that makes sense and is what I expected, but then... why does this say the tag was last update "a day ago"? https://hub.docker.com/layers/ruby/library/ruby/2.5.7/images/sha256-d6fe46d783a225c566c6f2be83db7d9d95f9928df77402223914e4010aa2d502

Am I looking at the wrong image/repo or something?

**Comment by wglambert** [comment]
The base image Debian was updated, which causes all images built from it to be rebuilt
https://github.com/docker-library/official-images/pull/7386
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/debian/78/

So if you use `ruby:2.7.0-buster` then you'd only get updates when 2.7.0 has a patch, or when Debian Buster updates.

If you use the images [sha256 hash](https://github.com/docker-library/repo-info/blob/master/repos/ruby/remote/2.7.0-buster.md) you will lock in that version and never get updates on it. Additionally using a tag like `ruby:2.7-buster` will give you minor version updates with Buster changes

**Comment by mltsy** [comment]
Ah!  Thank you - that helps :)  Looks like it's not easy to tell how often these have been updated in the past, but it seems at least that all the Debian images are updated at once (so one flavor is not going to be less active than another in terms of update frequency?) - so either using a specific SHA hash or creating our own image repository/tags, based on these ones, would be the best ways to get more control over the update timelines.

Thanks very much for the clarification, @wglambert!

**Comment by yosifkit** [comment]
All the base Debian images are updated at least monthly (more often if there is an important security fix to apply, like https://github.com/docker-library/official-images/issues/2171).
