### ISSUE TITLE
please roll updated images with today's security fixes

### ISSUE THREAD

**Issue by modosc** [docker-library/ruby#311]
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-5-8-released/
https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-4-10-released/

**Comment by tianon** [comment]
See https://github.com/docker-library/ruby/pull/310 and https://github.com/docker-library/official-images/pull/7718.

**Comment by modosc** [comment]
@tianon thanks!
