### ISSUE TITLE
2.7-alpine requires ruby version 2.7.1

### ISSUE THREAD

**Issue by iRichLau** [docker-library/ruby#314]
Hi, I am using the 2.7-alpine image but it requires that I use upgrade to 2.7.1 

`Your Ruby version is 2.7.1, but your Gemfile specified 2.7.0`

What is the difference between using 2.7.1-alpine image and 2.7-alpine image if both requires me to use ruby 2.7.1? Thanks!

**Comment by yosifkit** [comment]
Pulling `2.7-alpine` will get the latest `2.7.x`. So to "pin" to a specific version to use with your gemfile, you would have to use `2.7.0-alpine` (which is no longer updated/supported).
