### ISSUE TITLE
Update to Rubygems 3.1.4

### ISSUE THREAD

**Issue by md5** [docker-library/ruby#322]
We recently started using the Ruby 2.7.1 image (`ruby:2.7.1-slim-buster` to be precise) and ran into this issue that was recently fixed in Rubygems 3.1.3: https://github.com/rubygems/rubygems/pull/3458

Looks like the Docker image is currently using 3.1.2:

```console
$ docker run --rm ruby:2.7.1-slim-buster gem --version
3.1.2
```

Running `gem update --system` is a workaround, but it would be great to get a refreshed image with up-to-date Rubygems.

**Comment by tianon** [comment]
:wave:!!

See https://github.com/docker-library/ruby/issues/246 and https://github.com/docker-library/ruby/pull/255 -- we intentionally stopped explicitly bumping (or even specifying) the RubyGems version :disappointed:

So unfortunately, you'll need to either petition Ruby upstream to do a new release with a newer bundled RubyGems or do the explicit upgrade as you've discovered.

**Comment by md5** [comment]
Thanks @tianon! We've done the `gem update --system` for the moment
