### ISSUE TITLE
Why Ruby is installed through os package manager (apt-get) and then through source?

### ISSUE THREAD

**Issue by jpmolinamatute** [docker-library/ruby#334]
I'm looking at this [line](https://github.com/docker-library/ruby/blob/cf2a6f335a0db67d6d1c957d8d396e5f8ee0cce3/2.7/buster/slim/Dockerfile#L50) and this [one](https://github.com/docker-library/ruby/blob/cf2a6f335a0db67d6d1c957d8d396e5f8ee0cce3/2.7/buster/slim/Dockerfile#L56)

**Comment by tianon** [comment]
Ruby's build system requires/uses Ruby, so we install (and then later remove) the system Ruby packages.
