### ISSUE TITLE
Issue with alpine 3.13 on ruby-2.5.8 base image

### ISSUE THREAD

**Issue by mehyedes** [docker-library/ruby#340]
We have noticed that `apk` on alpine 3.13 has an issue when used behind a proxy.
Which is explained in the issue below on the docker-alpine repository:
https://github.com/alpinelinux/docker-alpine/issues/136

Our builds that are based on the `ruby-2.5.8-alpine` base image started failing after this recent alpine version upgrade:
https://github.com/docker-library/ruby/pull/337

Fetching packages is not possible anymore from the alpine repos:
```
Step 1/19 : FROM ruby:2.5.8-alpine
 ---> b14dcd6b80e9
...
 ---> Running in dac64a889b9f
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
[91mERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
[0m[91mERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
[0m2 errors; 36 distinct packages available
```

Seems that replacing http with https solves the issue according to this [comment](https://github.com/alpinelinux/docker-alpine/issues/98#issuecomment-679306519) (haven't tested it myself). However, I thought I'd raise this issue here in case it is not already known to the maintainers. 

**Update:**
~~Downgrading to 3.12 would be an option~~
Just noticed that `ruby:2.5.8-alpine3.12` is also available. The alpine-3.13 based image is unusable though
Also, after testing, confirmed that replacing `https` with `http` in `/etc/apk/repositories` as a workaround solves the issue:
```
 ---> Running in c415bdc6cb8c

fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz

v3.13.0-150-gd0fe42c217 [http://dl-cdn.alpinelinux.org/alpine/v3.13/main]

v3.13.1-2-gf5e128b248 [http://dl-cdn.alpinelinux.org/alpine/v3.13/community]

OK: 13881 distinct packages **available**
```

**Comment by tianon** [comment]
Given this is an upstream Alpine issue, there's unfortunately not much we can do about it (however, as noted in https://github.com/alpinelinux/docker-alpine/issues/136#issuecomment-769922932, it should be fixed now).
