### ISSUE TITLE
Schemantic error in verification no system-ruby packages installed Dockerfile

### ISSUE THREAD

**Issue by clushie** [docker-library/ruby#341]
This line

https://github.com/docker-library/ruby/blob/e040029c82501556371e9d84a9db607dfb1bba51/Dockerfile-slim.template#L101-L102

won't work as expected. Because of the `!` it will always succeed.

Shellcheck tracks this behavior with

```bash
! dpkg -l | grep -i ruby
^-- SC2251: This ! is not on a condition and skips errexit. Use `&& exit 1` instead, or make sure $? is checked.
```

I can't see a clean one-liner to solve this, I think the correct way is to rather run:

`if dpkg -l | grep -i 'ruby'; then return 1; fi`

also `dpkg -l` can list previously uninstalled packages, to verify a package is actually installed it would rather be `| grep -iP '^ii.*ruby.*'`

**Comment by tianon** [comment]
Just to tug on https://github.com/docker-library/ruby/pull/342#issuecomment-783565389 (trust, but verify):

> (Also, IMO it's worth verifying that the current code actually does fail to exit properly when `ruby` is installed.)

I tried this out with the following diff:

<details>
<summary>Diff:</summary>

```diff
diff --git a/3.0/alpine3.13/Dockerfile b/3.0/alpine3.13/Dockerfile
index 77dabff..731d56d 100644
--- a/3.0/alpine3.13/Dockerfile
+++ b/3.0/alpine3.13/Dockerfile
@@ -103,6 +103,7 @@ RUN set -eux; \
                procps \
                yaml-dev \
                zlib-dev \
+               ruby \
        ; \
        apk del --no-network .ruby-builddeps; \
        \
diff --git a/3.0/buster/Dockerfile b/3.0/buster/Dockerfile
index 0f81bb7..b4b0e90 100644
--- a/3.0/buster/Dockerfile
+++ b/3.0/buster/Dockerfile
@@ -56,7 +56,7 @@ RUN set -eux; \
        make install; \
        \
        apt-mark auto '.*' > /dev/null; \
-       apt-mark manual $savedAptMark > /dev/null; \
+       apt-mark manual $savedAptMark ruby > /dev/null; \
        find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' \
                | awk '/=>/ { print $(NF-1) }' \
                | sort -u \
```

</details>

(The build does indeed succeed! :scream: :disappointed: :+1:)
