### ISSUE TITLE
concurrent `bundle install` for onbuild tags

### ISSUE THREAD

**Issue by buth** [docker-library/ruby#35]
The bundle install step could likely by dramatically sped up by adding `--jobs 4` or some such value.

http://bundler.io/v1.5/bundle_install.html#jobs

**Comment by yosifkit** [comment]
What if we do `--jobs $(nproc)`?  Would that be bad in some cases?  Does it make sense to force a job number on everyone, especially those with older machines that might not handle the load?

Any thoughts @tianon?

**Comment by buth** [comment]
Could it be set to an environment variable, the default of which could be set in the Dockerfile as 1?

**Comment by yosifkit** [comment]
Unfortunately, there is currently no way to change the environment variables during build.

**Comment by buth** [comment]
Ah, right.

**Comment by buth** [comment]
Wouldn't a subsequent redefinition of the environment variable in the including Dockerfile win out? Say if I immediately had an `ENV` line after my `FROM ruby:2.2.0-onbuild`?

**Comment by yosifkit** [comment]
Nope, :cry:, `ONBUILD` directives happen first.

**Comment by tianon** [comment]
We actually considered doing this before.  The reason `$(nproc)` is mostly reasonable in places like compiling an application is that if `nproc` is 8, for example, `make -j8` leads to roughly 8 concurrent `gcc` processes, which is reasonable for an 8-core CPU.  Here, `--jobs` is how many Gems to build in parallel, which themselves might parallelize, so `--jobs 8` might actually lead to 16 or more concurrent processes.  For Gentoo users, this is essentially the same as `emerge --jobs` versus `-j` in `MAKEOPTS`.

Also, the main `Dockerfile` is pretty much only built on our machines during testing and on the official build server, where these `ONBUILD` directives usually build on the user's machine, where being a more conservative citizen is important. :disappointed:

**Comment by nightscape** [comment]
There is an open PR (hopefully ready to merge soon) that allows specifying build-time environment variables. If that PR lands, would it be an option to use it here?

**Comment by yosifkit** [comment]
That might be possible, though not until at least Docker 1.7 and even then, we have to do it in a way that is backwards compatible with versions all the way back to 1.0.  The easy way is to just put these commands in your Dockerfile, rather than just `FROM ruby:onbuild`; that way you can customise any part, including adding any apt installs that might be necessary.

**Comment by yosifkit** [comment]
Closing old issue. Closed by https://github.com/docker-library/docs/pull/911.
