### ISSUE TITLE
Updates needed for Ruby 3.0.2, 2.7.4, and 2.6.8

### ISSUE THREAD

**Issue by md5** [docker-library/ruby#350]
New versions of Ruby were released yesterday, July 7, 2021. Should just be a matter of running `update.sh` to cut new releases.

**Comment by md5** [comment]
I should note that there are CVE fixes associated with these new releases

**Comment by yosifkit** [comment]
They should already be built and available: https://github.com/docker-library/official-images/pull/10495. :+1:

**Comment by tianon** [comment]
"No disassemble @md5; @md5 ... ALIVE!" (good to see you again :heart:)

**Comment by md5** [comment]
Thanks @yosifkit! I should have checked more thoroughly. Looks like this is an issue with the internal Docker Hub mirror here at Disney that I have to track down with our folks here 😖 

Hi @tianon 👋
