### ISSUE TITLE
ruby OpenSSL missing/miss-matched dependencies

### ISSUE THREAD

**Issue by markstephens** [docker-library/ruby#353]
Hi

I am seeing an issue with Alpine ruby where something is not lining up, either between ruby, active support in Rails or the Alpine image itself. Posting here as I _think_ it's the best place to start! Thanks in advance!

I am building a brand new rails 6.1.4 app and using the `ruby:3.0.2-alpine` docker image.

My Dockerfile builds ok, but I get this error when starting the app.
```
/usr/local/bundle/gems/activesupport-6.1.4/lib/active_support/key_generator.rb:23:in `generate_key': uninitialized constant OpenSSL::PKCS5 (NameError)
Did you mean?  OpenSSL::PKCS7
               OpenSSL::PKCS12
```

This says to me that there is a dependency missmatch between what [active support is expecting](https://github.com/rails/rails/blob/76694ccd1b7e7eb50350718d6e7e7ce67033299f/activesupport/lib/active_support/key_generator.rb#L40) to be present and what the Ruby within the Alpine image is providing - i.e. it's expecting `OpenSSL::PKCS5` to be there

To recreate this issue:
1. `rails new docker_test`
2. Add attached Dockerfile to the project root
3. Docker build and run

**Dockerfile**
```Dockerfile
FROM ruby:3.0.2-alpine
RUN apk --update --upgrade add \
  build-base \
  sqlite-dev \
  tzdata
WORKDIR /app
# Bundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install
EXPOSE 3000
# Copy application
COPY . .
CMD bundle exec rails server -b '0.0.0.0'
```

I have tried a couple of things to resolve it, such as adding `openssl` to my Gemfile and installing openssl-dev package using apk, but they didn't work. I also tried `ruby:3.0.2-alpine3.13` but it did the same thing.

The reason why I am posting here, is if I change from the Ruby Alpine docker image to the normal full-fat Ruby image the same rails app works fine, so I'm guessing it's something related to the Alpine version.

e.g. This works
```Dockerfile
FROM ruby:3.0.2
WORKDIR /app
# Bundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install
EXPOSE 3000
# Copy application
COPY . .
CMD bundle exec rails server -b '0.0.0.0'
```
Gemfile for completeness
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

Thanks for any help.

**Comment by markstephens** [comment]
I tried with an older version of Ruby `ruby:2.7.4-alpine3.14` still on Alpine and **it does work ok**

This is the same docker file as above, just with different ruby version
```Dockerfile
FROM ruby:2.7.4-alpine3.14
RUN apk --update --upgrade add \
  build-base \
  sqlite-dev \
  tzdata
WORKDIR /app
# Bundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install
EXPOSE 3000
# Copy application
COPY . .
CMD bundle exec rails server -b '0.0.0.0'
```

**Comment by tianon** [comment]
I think this is probably something related to doing `rails new` on your host (and thus embedding files that are compiled for your host environment into the resulting directory).  I _think_ you should be able to exclude some of those via `.dockerignore`, but I'm not sure exactly which directories you'll need to `.dockerignore` to get it to do the right thing.

I was not able to reproduce an issue using something like the following:

```dockerfile
FROM ruby:3.0-alpine
RUN apk add --no-cache build-base sqlite-dev tzdata
RUN gem install rails -v 6.1.4
RUN apk add --no-cache yarn # needed for webpacker
RUN rails new docker_test
WORKDIR /docker_test
CMD ["rails", "server", "-b", "0.0.0.0"]
```

**Comment by markstephens** [comment]
Thanks @tianon 

I think you are correct, I have done some experimenting...

First, I could also successfully build and run your Dockerfile, so I thought you might be correct that something specific to my host is being embedded into the docker image.

So, with the aim of working out what those files are, I compared the files generated by `rails new` that has been run in the container (your Dockerfile) and directly on the host (as I was previously doing) - they were pretty identical, I couldn't see anything obvious that referenced the host versions of ruby.

I did have some conflicts with an older version of ruby installed by apt, so I sorted that out -  I think this was the main problem really.

I'm now in a place where my above test case does work properly.

However, I'm still getting an issue on the real app I'm building where it works if I copy files into the image, but mounting the same dir as a volume gives me the openssl error again. e.g.

- Dockerfile has `COPY . .` in it
- `docker run -it <image id> rails s` works :+1: 
- `docker run -it <image id> -v /local/path/:/app rails s` does not work :-1: 

But I can't reproduce this in a test case... It's very strange, I don't see what could be causing it.

I think you can close the issue though, it must be something I am doing somewhere..

**Comment by markstephens** [comment]
I managed to fix my issue. I had some old bit of code in my app, coupled with old ruby versions as mentioned previously.
Thanks for your help.
Closing the issue now
