### ISSUE TITLE
Gem Bundler Install Permission Issues

### ISSUE THREAD

**Issue by andygnelson** [docker-library/ruby#354]
Starting on or around July 8th my builds started failing with permissions issues on the /usr/local/bundle directory which makes no sense because that directory is given 777 permissions according to the Dockerfile. The base image I was using was ruby:2.6-alpine, I upgrade to ruby:3.0.2-alpine3.14 to attempt to fix the issue and that did not work.

I did however downgrade to ruby:2.6-alpine3.13 and that seems to have resolved my issue, though I do not have the foggiest idea why. I am not a Ruby developer typically it just has good octokit libraries that I use.

My best guess is an issue with the latest alpine version since initially I did not specify the version and if it failed, 3.14 failed, but 3.13 did not fail with this error.

Step 3/10 : RUN gem install bundler
 ---> Running in f35c54c4a444
[91mERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/local/bundle directory.
[0mService 'tech_debt' failed to build: The command '/bin/sh -c gem install bundler' returned a non-zero code: 1

**Comment by wglambert** [comment]
Looks like https://github.com/docker-library/ruby/issues/351

**Comment by andygnelson** [comment]
@wglambert yes that looks exactly like my issue with the exception of how it presents. None of my google searches apparently landed me on the right issue, hopefully me issue serves as a bit of a redirection since I assume gem bundler install is fairly common. I guess I shouldn't be using the bare alpine tag.
