### ISSUE TITLE
Plan to 3-bullseye?

### ISSUE THREAD

**Issue by kyontan** [docker-library/ruby#356]
Hello, I met a problem with `ruby:3` (equivalent to `ruby:3.0.2-buster`) and Apple Silicon (M1) Mac environment.

https://docs.docker.com/docker-for-mac/release-notes/#known-issues

According to the known issues of Docker for Mac, the `debian:buster`, ancestor image of `ruby:3.0.2-buster` have a problem with libssl and causes a problem in Apple Silicon Macs.
It is noted that the `debian:bullseye` solves the problem about it.

Docker Hub provides `build-deps:bullseye` (that is base image of `ruby:3.0.2-buster`), so I have experimented to build `ruby:3.0.2-bullseye`.
I have confirmed that the libssl-related problem was solved.

<img width="509" alt="スクリーンショット 2021-08-07 15 53 24" src="https://user-images.githubusercontent.com/802339/128597020-b23b9e99-e854-4e49-9ae9-585c17c61581.png">

I know that the debian bullseye is not yet released as stable (planned 2021-08-14: https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html), but many people using Apple Silicon devices will have met the problem.

Is there a plan to release ruby images based on `debian:bullseye`? Hopefully, next week? (as soon as bullseye released)

Thanks,

**Comment by tianon** [comment]
> Is there a plan to release ruby images based on `debian:bullseye`? Hopefully, next week? (as soon as bullseye released)

Yep, after the official release is the plan.

**Comment by ojab** [comment]
https://github.com/docker-library/ruby/pull/357
