### ISSUE TITLE
FFI stopped working after upgrading from buster to bullseye

### ISSUE THREAD

**Issue by bb** [docker-library/ruby#359]
Thanks for keeping this image up-to-date by providing a bullseye variant.

We're depending only on Ruby versions (Tag `2.7.4` or `3.0.2`) so far. With the upgrade from buster to bullseye we get build errors:

```
LoadError: cannot load such file -- 2.7/ffi_c
```

and

```
LoadError: cannot load such file -- 3.0/ffi_c
```

Changing the tag to buster to e.g. `2.7.4-buster` fixed the build error.

If this is something which needs to be fixed e.g. in the ffi gem, feel free to close this issue, ideally with a hint how to fix the issue.

**Comment by bb** [comment]
Nevermind... this was my fault. I had to clear the Gitlab CI runner caches where the gems compiled against Buster were cached.

**Comment by heycassidy** [comment]
I'm using this docker image (ruby version 3.0.2) with bitbucket pipelines and I got the exact same error.
Changing my pipelines image identifier from `image: ruby:3.0.2` to `image: ruby:3.0.2-buster` fixed it.
