### ISSUE TITLE
Ruby archive downloaded over insecure link

### ISSUE THREAD

**Issue by bladealslayer** [docker-library/ruby#36]
Ruby archives are downloaded over HTTP and checksums are not verified. Checksums are published on official website, and since the versions seem hardcoded in `Dockerfile`, the checksums could also be added.

**Comment by yosifkit** [comment]
Good catch, we've been trying to fix all the installs to be more secure.  We should definitely add the checksums like we do with other images, but it looks like `cache.ruby-lang.org` isn't available over ssl.

**Comment by bladealslayer** [comment]
:+1:  Yeah, no valid SSL on cache, but at least the checksums are published on an SSL-enabled site: https://www.ruby-lang.org/en/downloads/
