### ISSUE TITLE
Use GLIBC 2.34

### ISSUE THREAD

**Issue by TheEvilSkeleton** [docker-library/ruby#363]
Hi, I use a Toolbox container (Docker for development environments) because I prefer using containers in general. However, in the newer versions of Toolbox, it's asking for a recent version of GLIBC. I'd like to have an updated version of GLIBC so I can run Jekyll inside a Toolbox container.

Here's the error:

```
❯ podman start --attach jekyll-toolbox 
toolbox: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by toolbox)
```

Related to containers/toolbox#821.

Here's the [Dockerfile](https://gitlab.com/TheEvilSkeleton/jekyll-toolbox/-/blob/main/Dockerfile).

**Comment by wglambert** [comment]
For the Debian variants the most up to date version of glibc is 2.31 https://packages.debian.org/bullseye/libc6
And experimental is on 2.33 https://packages.debian.org/experimental/libc6
