### ISSUE TITLE
platform information not present on the arm64v8

### ISSUE THREAD

**Issue by wdiechmann** [docker-library/ruby#374]
`docker manifest inspect arm64v8/ruby:3.0.3`

this is unfortunate 'cause Docker will report containers FROM arm64v8/ruby:3.0.3 as `aarch64-linux` - which further down the "road" makes for bad compiler decisions otherwise 😢 

any chance of a quick remedy? 

tried FROM --platform=linux/arm64/v8 arm64v8/ruby:3.0.3 which I am sad to report meet with no success (other than Docker keep reporting aarch64-linux

**Comment by tianon** [comment]
Can you maybe give a little more detail about what you're trying to do, what's happening, and what you expect to happen instead?

For example, "Docker keep reporting aarch64-linux" doesn't really tell us much -- reporting where?  What commands are you running to get it to report that?

**Comment by wdiechmann** [comment]
I linked to an issue I've opened on rails/tailwindcss-rails and cutting to the chase what I'm trying is running Rails 7.0.0 in a container. It does run - kind of - but with Rails 7 you get an opportunity to skip having `node` based scripts extracting necessary javascript and css; that, however, requires the platform being one of

      "arm64-darwin" => "tailwindcss-macos-arm64",
      "x64-mingw32" => "tailwindcss-windows-x64.exe",
      "x86_64-darwin" => "tailwindcss-macos-x64",
      "x86_64-linux" => "tailwindcss-linux-x64",

and during my googling of ways to make that happen I was lead to understand that building my container off of an arm64v8/ruby would see that happen. That did not happen and now my predicament seems to be that my recent M1 has turned out to be more of a drag than a productivity boost 😢 

I've run containers for years - enjoying the comfort of moving effortless from one ruby version to another and errecting entire 'stacks' and throwing them away again in a matter of, well if not minutes than a few hours.

With M1 I was forced 'cause `brew` would require some serious handholding to provide - but I was not intimidated as I was comfortable with containers.

That seems all to be negated by my recent findings - and I wonder how the rest of the "M1 community" is holding up 🤔 

My apologies for not being able to succinctly present my case  -

**Comment by yosifkit** [comment]
Since they don't provide an `arm64v8` Linux build then your best option to keep it in a container is to use the `amd64` images either via the `--platform` flag on the `docker` commands or by using the `amd64` Docker Official Images images directly: https://hub.docker.com/u/amd64.  Docker for Mac should already have put in place the bits needed for emulating `x86_64` images on the M1-based Mac.

**Comment by wdiechmann** [comment]
well - yeah - I'm with you but guess what!

Running `docker build --platform linux/x86_64 .` did the trick - which surely must be a "feature" - - I've had `platform: linux/x86_64` in my docker-compose.yml since like forever (or at least since I swapped my Intel Macbook Pro for the M1) and further I've tested it with a couple other containers - mariadb and mysql -

`docker build` _respects_ the  **platform** argument - docker-compose does not (I know, it's a terrible accusation but I'll try to validate it in a little while - now I have to hurry and get like 7-8 containers back up and running 🚀 

A huge thx @yosifkit for staying with me - and the `x86_64 ` was the cue to try it out once more!

**Comment by wdiechmann** [comment]
hmm - I could have sworn docker-compose build would pick a 'wrong' base image not respecting the platform - but I'm not able to reproduce it, so the verdict is: keep your `platform: linux/x86_64` close when building containers for running apps that require some kind of x86 "hardware" compliance.
