### ISSUE TITLE
Update Docker base image ruby:2.6.6-slim for Security updates

### ISSUE THREAD

**Issue by gameiro** [docker-library/ruby#375]
Hi Guys,

Is it possible to run and update the ruby docker image tag: `2.6.6-slim` to update the security packages ? 

This current image tag as lot of vulnerabilities that could be fixed by just running the OS update and upgrade. 

Is this possible ? 

Regards

Carlos

**Comment by tianon** [comment]
Unfortunately, Ruby 2.6.6 is no longer supported -- if you want security updates, you'll need to update to 2.6.9 (or higher minor/major releases).
