### ISSUE TITLE
Ruby on Rails RedCloth issue when using Docker on Apple M1 hardware

### ISSUE THREAD

**Issue by mo-nathan** [docker-library/ruby#385]
When using the RedCloth gem under Ruby on Rails in a Docker container on an Apple M1 system, the string get truncated just before the first non-ascii character. The problem does not happen on an Apple Intel system or if Rails is run outside of Docker. This GitHub repo should reproduce the issue on any Apple M1 hardware:

https://github.com/mo-nathan/docker-test

I'm guessing it has something to do with how the standard ruby Docker images are getting created for Apple M1s. I've tried tracing the issue using a Ruby debugger, but haven't found any additional clues.

I have also posted this question to stackoverflow here:

https://stackoverflow.com/questions/72738254/ruby-on-rails-redcloth-issue-when-using-docker-on-apple-m1-hardware

**Comment by tianon** [comment]
Interesting!  Can you reproduce with other builds of Ruby, like maybe the ones you can install via `apt-get` in Debian?  (My guess is that there's something going on with RedCloth or one of the dependencies it needs/uses, but I'm definitely guessing. :grimacing:)
