### ISSUE TITLE
Crash apt-get update

### ISSUE THREAD

**Issue by RicardoLemeIterative** [docker-library/ruby#393]
Good morning, when creating my docker file I'm having error running the command "apt-get update" I'm taking the ruby version 2.2

![image](https://user-images.githubusercontent.com/119059121/204002453-79edc882-eaa7-4648-9d1b-834de75605b2.png)

**Comment by wglambert** [comment]
https://unix.stackexchange.com/a/508728
>if you want to continue fetching Jessie backports, you need to use archive.debian.org instead
