### ISSUE TITLE
Why does an image built with arm64v8/ruby report aarch64-linux?

### ISSUE THREAD

**Issue by theRocket** [docker-library/ruby#403]
This is upsetting my bundle install process when I try to lock the platform:
Dockerfile:
```
FROM arm64v8/ruby:2.7.6-buster
```
The results of bundle install:
```
root@9e035d6f6aea:/var/task# bundle install
Your bundle only supports platforms ["arm64-linux"] but your local platform is aarch64-linux. Add the current platform to the lockfile with
`bundle lock --add-platform aarch64-linux` and try again.
```
The output from ruby version:
```
root@9e035d6f6aea:/var/task# which ruby
/usr/local/bin/ruby
root@9e035d6f6aea:/var/task# ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [aarch64-linux]
```
Should I try to lock it to `aarch64-linux`? I am trying to build for the new ARM64 compatible architecture on a ruby layer for an AWS Lambda on Ruby 2.7 runtime.
https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by yosifkit** [comment]
:confused: `arm64v8` means the same as `aarch64`. Is there more to your Dockerfile or something in the `Gemfile` or `Gemfile.lock`?
