### ISSUE TITLE
ruby 2.3.1 suddenly stopped working with apt-get update

### ISSUE THREAD

**Issue by luke-hill** [docker-library/ruby#409]
Has something changed recently with the apt-get mirrors when being read by ruby 2.3.1 bases

(Yes I'm aware this is an ancient base, bear with me).

I did a lot of work to make this working around 2-3 weeks ago. I tried to rebuild containers today using --no-cache and hitting lots of new errors.

Dockerfile (Stripped down is)

```
FROM ruby:2.3.1

ENV APP_HOME=/app \
    LANG=C.UTF-8

RUN mkdir -p $APP_HOME

WORKDIR $APP_HOME

RUN apt-get update
```

Updating to `ruby:2.4` works. I'm trying to see if other `ruby:2.3.x***` images work but no dice so far.

Errors are...

```
 > [stage-0  4/13] RUN apt-get update &&     apt-get clean:                     
#0 1.035 Ign http://deb.debian.org jessie InRelease                             
#0 1.052 Ign http://security.debian.org jessie/updates InRelease                
#0 1.064 Ign http://deb.debian.org jessie-updates InRelease                     
#0 1.067 Ign http://security.debian.org jessie/updates Release.gpg
#0 1.082 Ign http://security.debian.org jessie/updates Release
#0 1.086 Ign http://deb.debian.org jessie Release.gpg
#0 1.098 Err http://security.debian.org jessie/updates/main amd64 Packages
#0 1.098   
#0 1.100 Ign http://deb.debian.org jessie-updates Release.gpg
#0 1.117 Err http://security.debian.org jessie/updates/main amd64 Packages
#0 1.117   
#0 1.120 Ign http://deb.debian.org jessie Release
#0 1.134 Ign http://deb.debian.org jessie-updates Release
#0 1.135 Err http://security.debian.org jessie/updates/main amd64 Packages
#0 1.135   
```

Followed by some IP stacktraces.

Any advice/recommendations greatly appreciated. I've tried doing a variety of `sed` commands gleaned from SO to try fix things. These only partially work as then things like `apt-get install pandoc` fails with another weird error.

**Comment by yosifkit** [comment]
Like Ruby 2.3, Debian Jessie is also long past end of life (and [LTS](https://wiki.debian.org/LTS)). Some possible workarounds in https://github.com/docker-library/ruby/issues/394, but I think it was finally pulled from Debian mirrors and so those may not work at all.
