### ISSUE TITLE
Why set ENV vars that change default behavior?

### ISSUE THREAD

**Issue by treeder** [docker-library/ruby#42]
https://github.com/docker-library/ruby/blob/69582bf7de57fe358d4c3c7c23400aebaf626b92/2.2/Dockerfile#L36

These things mess up things like bundle install --standalone, why not just let it install where bundler/gem would normally install it?

**Comment by md5** [comment]
This change was introduced in #21. There isn't much discussion there, but I figured I'd link it anyways.

**Comment by yosifkit** [comment]
That was added to facilitate a "normal" developer workflow:
- Dockerfile with `COPY . /usr/src/app` and `RUN bundle install`
  - application src and deps are ready to go when using same Dockerfile to build for QA and prod
- developer runs with `-v /local/code/dir:/usr/src/app`
  - no "missing" `.bundle` file when running app
  - live changes when editing source
  - usually add an entrypoint script to run `bundle install` so that new deps can be tested by running a new container and not needing to rebuild the image

**Comment by tianon** [comment]
Also, if that ".bundle" directory is created on the host, the chances of it
working inside the container without being fully rebuilt are very low.  The
same is true of the reverse -- ".bundle" created inside the container is
very unlikely to work on the host, or even potentially in a newer version
of the image (although that's much less likely to be problematic).

**Comment by tianon** [comment]
As an additional benefit, forcing "bundle install" and "gem install"
to put gems in the same place means that you can do things like "RUN
gem install some-module" to essentially pre-seed your image with gems
before you copy in your Gemfile, thus further improving caching and
overall image rebuild speed.

**Comment by treeder** [comment]
I understand what you're saying here and I agree with these things, but I'm not sure I understand why you'd change it from the defaults for Ruby. I don't see any advantage, but there are disadvantages in that it breaks things that should work. Here are two outputs, one from the 'ruby' image with these ENV variables overriding defaults and one from a normal Ruby install without overriding ENV variables. 

```
docker run --rm -v "$(pwd)":/app -w /app ruby sh -c 'bundle install && bundle show iron_mq && ls -al'
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from http://rubygems.org/...........
Fetching version metadata from http://rubygems.org/..
Installing net-http-persistent 2.9.4
Installing netrc 0.10.3
Installing rest 3.0.6
Installing iron_core 1.0.7
Installing iron_mq 5.0.1
Using bundler 1.9.0
Bundle complete! 1 Gemfile dependency, 6 gems now installed.
Bundled gems are installed into /usr/local/bundle.
/usr/local/bundle/gems/iron_mq-5.0.1
total 20
drwxr-xr-x  1 1000 staff  204 Apr 18  2015 .
drwxr-xr-x 53 root root  4096 Apr 18 13:30 ..
-rw-r--r--  1 1000 staff   45 Apr 15 23:05 Gemfile
-rw-r--r--  1 1000 staff  294 Apr 18 13:27 Gemfile.lock
-rw-r--r--  1 1000 staff  583 Apr 18  2015 README.md
-rw-r--r--  1 1000 staff   72 Apr 15 23:35 hello.rb
```

And from an image with default ruby install: 

```
docker run --rm -v "$(pwd)":/app -w /app iron/images:ruby-2.1 sh -c 'bundle install && bundle show iron_mq && ls -al'
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from http://rubygems.org/...........
Installing net-http-persistent 2.9.4
Installing netrc 0.10.3
Installing rest 3.0.6
Installing iron_core 1.0.7
Installing iron_mq 5.0.1
Using bundler 1.7.4
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
/usr/local/lib/ruby/gems/2.1.0/gems/iron_mq-5.0.1
total 20
drwxr-xr-x   1 1000 staff  204 Apr 18  2015 .
drwxr-xr-x 137 root root  4096 Apr 18 13:31 ..
-rw-r--r--   1 1000 staff   45 Apr 15 23:05 Gemfile
-rw-r--r--   1 1000 staff  294 Apr 18 13:27 Gemfile.lock
-rw-r--r--   1 1000 staff  702 Apr 18  2015 README.md
-rw-r--r--   1 1000 staff   72 Apr 15 23:35 hello.rb
```

Very little difference here in terms of usage and location, but the second one doesn't break things like `bundle install --standalone`.

**Comment by md5** [comment]
@treeder are you sure this isn't a bug in Bundler?

Also, it might be helpful if you could change your two tests commands to use `bundle install --standalone` so that we could see the actual error.

**Comment by treeder** [comment]
I don't know if it's a bug in Bundler, but again, I'm trying to understand why you'd change the defaults when they do nearly the same thing anyways without changing what people expect. What's the benefit of overriding those things?

Here's the output with --standalone:

```
docker run --rm -v "$(pwd)":/app -w /app ruby sh -c 'bundle install --standalone && bundle show iron_mq && ls -al'
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from http://rubygems.org/...........
Fetching version metadata from http://rubygems.org/..
Installing net-http-persistent 2.9.4
Installing netrc 0.10.3
Installing rest 3.0.6
Installing iron_core 1.0.7
Installing iron_mq 5.0.1
Using bundler 1.9.0
Bundle complete! 1 Gemfile dependency, 6 gems now installed.
Bundled gems are installed into /usr/local/bundle.
/usr/local/bundle/gems/iron_mq-5.0.1
total 20
drwxr-xr-x  1 1000 staff  272 Apr 20 15:18 .
drwxr-xr-x 53 root root  4096 Apr 20 15:20 ..
drwxr-xr-x  1 1000 staff  102 Apr 20 15:18 .bundle
-rw-r--r--  1 1000 staff   45 Apr 15 23:05 Gemfile
-rw-r--r--  1 1000 staff  294 Apr 18 13:27 Gemfile.lock
-rw-r--r--  1 1000 staff  703 Apr 18 13:50 README.md
drwxr-xr-x  1 1000 staff  136 Apr 20 15:18 bundle
-rw-r--r--  1 1000 staff   72 Apr 15 23:35 hello.rb
```

Notice it installs it at the overridden location. Here's a normal Ruby install: 

```
docker run --rm -v "$(pwd)":/app -w /app iron/images:ruby-2.1 sh -c 'bundle install --standalone && bundle show iron_mq && ls -al'
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from http://rubygems.org/...........
Installing net-http-persistent 2.9.4
Installing netrc 0.10.3
Installing rest 3.0.6
Installing iron_core 1.0.7
Installing iron_mq 5.0.1
Using bundler 1.7.4
Your bundle is complete!
It was installed into ./bundle
/app/bundle/ruby/2.1.0/gems/iron_mq-5.0.1
total 20
drwxr-xr-x   1 1000 staff  272 Apr 20 15:18 .
drwxr-xr-x 136 root root  4096 Apr 20 15:18 ..
drwxr-xr-x   1 1000 staff  102 Apr 20 15:18 .bundle
-rw-r--r--   1 1000 staff   45 Apr 15 23:05 Gemfile
-rw-r--r--   1 1000 staff  294 Apr 18 13:27 Gemfile.lock
-rw-r--r--   1 1000 staff  703 Apr 18 13:50 README.md
drwxr-xr-x   1 1000 staff  136 Apr 20  2015 bundle
-rw-r--r--   1 1000 staff   72 Apr 15 23:35 hello.rb
```

**Comment by yosifkit** [comment]
In looking for infomation about `--standalone` I found [André Arko](http://andre.arko.net/2014/06/27/rails-in-05-seconds/), and it looks like running your `bundle install` with `--path .bundle` would fix the problem.

**Comment by treeder** [comment]
Not looking for a workaround, just want to know why you would change it. Again, was there a reason for changing the default behavior?  I believe I had an issue with the golang image too, having changed defaults.

**Comment by md5** [comment]
@yosifkit and @tianon explained the rationale starting in this comment: https://github.com/docker-library/ruby/issues/42#issuecomment-94104255

**Comment by treeder** [comment]
All of those things seem to work without overriding the defaults.

**Comment by yosifkit** [comment]
@treeder, without these changes, the `.bundle` file would be created in the app directory and could be deleted by them, or modified in incompatible ways by their host if they also run ruby locally.

**Comment by treeder** [comment]
Your call. I came across the the Google one which is a pretty clean install and works for how I want it. See this post for reference: https://medium.com/@treeder/why-and-how-to-use-docker-for-development-a156c1de3b24
