### ISSUE TITLE
Support for ruby:3.0-bookworm

### ISSUE THREAD

**Issue by samruddhikhandale** [docker-library/ruby#422]
From https://github.com/docker-library/ruby/issues/397#issuecomment-1358111348 & https://github.com/docker-library/ruby/pull/392

> In Alpine 3.17, Openssl is 3 by default, so those images are already using it (and the reason for 2.7 and 3.0 not having Alpine 3.17 images). See https://github.com/docker-library/ruby/pull/392.

> Alpine 3.17 ships with openssl3 by default. Ruby 2.7 and 3.0 only build with openssl1, but there is a compat package which can be installed. I'm assuming that this will also be a problem for future debian versions.

I understand that this (☝️) is the same reason for not having a release of `ruby:3.0-bookworm`. 

My question, are there any plans of supporting `ruby:3.0-bookworm`? (by probably adding the compatibility package as mentioned above)

**Comment by tianon** [comment]
I don't think Debian has an OpenSSL 1.1 compatibility package for Bookworm.

**Comment by samruddhikhandale** [comment]
I see, @tianon does that mean there would NOT be an images release for `ruby:3.0-bookworm`? 
Also, would it be the same case for `php:8.0-apache-bookworm`? ([Ref](https://github.com/docker-library/php/pull/1348))

**Comment by tianon** [comment]
Correct - Ruby 3.0 has no plans to support OpenSSL 3, is already in "security maintenance" mode, and will be EOL shortly into next year (https://www.ruby-lang.org/en/downloads/branches/; 2024-03-31).

The same applies to PHP 8.0, although with an even tighter timeline (https://www.php.net/supported-versions.php; 26 Nov 2023).
