### ISSUE TITLE
Prou

### ISSUE THREAD

**Issue by Nunn4577** [docker-library/ruby#426]
Products
html meta tags for mobile devices
Asked 10 years, 8 months ago
Modified 2 years, 9 months ago
Viewed 45k times
15

I have a block of html code, which is mainly meta tags. I'm trying to re-design my layout for mobile devices, so I want to know if the meta tags that I'm using are necessary for a mobile layout. The block of code is provided below:

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE-edge,chrome=1">
<title>ConquestRealms - Home</title>
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="cleartype" content="on">

**Comment by yosifkit** [comment]
Seems like spam or accidental open.
