### ISSUE TITLE
Latest images seem to be built for the wrong architectures

### ISSUE THREAD

**Issue by krisrang** [docker-library/ruby#449]
On an M1 Mac with Docker Desktop running:

```
docker run --rm -it ruby:3.3.1-alpine apk --print-arch
armhf
```

```
docker run --rm -it ruby:3.3.0-alpine apk --print-arch
aarch64
```

```
docker run --rm -it ruby:3.3.1-slim-bookworm dpkg --print-architecture
armel
```

```
docker run --rm -it ruby:3.3.0-slim-bookworm dpkg --print-architecture
arm64
```

Same for amd64, it gives i386 instead.

**Comment by tianon** [comment]
This is expected -- the builds are still in progress, so Docker is pulling for you the "best" architecture supported by your host system.

**Comment by krisrang** [comment]
Ah I should've thought of that. Yea all works as expected now, thanks!
