### ISSUE TITLE
Change locale to c.utf-8

### ISSUE THREAD

**Issue by ubergesundheit** [docker-library/ruby#45]
As described [here](https://oncletom.io/2015/docker-encoding/), `en_US.UTF-8` is not available in debian jessie.

The link above also describes a solution, namely to include `ENV LANG C.UTF-8`

Could you please consider this?

**Comment by tianon** [comment]
I'm not _opposed_ to adding "ENV LANG C.UTF-8" by default, but I'd rather
see something more official from either Ruby or Rails upstreams
recommending a UTF-8 locale by default than just the anecdote that it's
"more common" or "more convenient".  If someone could find a good source
for that kind of discussion or documentation directly from upstream, that'd
push this over the edge into an easy and obvious change to make.

**Comment by mausch** [comment]
The Python image maintainers have fixed this about a year ago: https://github.com/docker-library/python/commit/dbe3e241f4c3263a81a888896f5126861807b3db .
Please just apply that here.

**Comment by yosifkit** [comment]
@mausch yes, we maintain both, but without an upstream discussion or recommendation, we'd rather not mandate a different locale.  I can only find the the default encoding for ruby scripts themselves is [uft8](http://ruby-doc.org/core-2.1.2/Encoding.html#class-Encoding-label-Script+encoding), but for most other [encoding](http://ruby-doc.org/core-2.1.2/Encoding.html#class-Encoding-label-Locale+encoding) it inherits from the locale with no recommendation of the default.

You could just create a short Dockerfile that's `FROM` this one and adds the locale and whatever else you need.  Combine that with [automated builds](https://docs.docker.com/docker-hub/builds/) and [repository links](https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with whatever you need added in.

**Comment by blackxored** [comment]
Is there an update on this issue? Was facing this too, and adding the `LANG` seems like a workaround to me, IMHO should be handled in the images.

**Comment by tianon** [comment]
http://docs.ruby-lang.org/en/2.1.0/Encoding.html#class-Encoding-label-External+encoding is the closest thing I've found so far to upstream recommending the default be `UTF-8` (and it's barely a hint) :disappointed:

**Comment by blackxored** [comment]
@tianon I've tried the workaround in a few instances and didn't work, only setting up locale worked.

**Comment by lfundaro** [comment]
Please merge this pull request. It took me a whole day to realised the big gotcha with debian jessie that they describe [here](https://oncletom.io/2015/docker-encoding/)  
other base containers using debian jessie are doing this by default. See [this](https://github.com/docker-library/openjdk/blob/2dd0496901a9c01c78895d0e6618b36c08f78bde/openjdk-8-jdk/Dockerfile#L19)
I am sure I am not the only one that went through this useless hassle. 
thanks.

**Comment by lfundaro** [comment]
@tianon maybe if you haven't found a good enough reason to merge this PR, would it be possible to warn users about this in the README ? I'm making a PR and will ping you for feedback

**Comment by dreyks** [comment]
This just bit me while I was moving my dev environment to a docker container. Googling lead me pretty fast to this issue, but still would be nice to document it somewhere

**Comment by ivan-kolmychek** [comment]
Just got the issue with this too. Documenting this may be a nice thing after all.

**Comment by james-powis** [comment]
this little tragedy of a feature cost me 4 hours of my sad little life... I think some form of a "just make it work" is needed...

**Comment by cyclotron3k** [comment]
Here's a reason to use `C.UTF-8`: It's not `US-ASCII`. Is that good enough?

Is docker trying to pull locale environment variables from the host system, and not finding `en_US.UTF-8` so defaulting to `US-ASCII`?

**Comment by Quintasan** [comment]
@yosifkit @tianon 
So almost 3 years after this has been reported this image is still using `POSIX` locale? Could you please give any rational argument apart from "upstream does not explicitly recommends that"? If I recall correctly then UTF-8 is backwards compatible with ASCII so this *should not* introduce any breakage. Even if it does then we can have people change the encoding back via `LOCALE` env variable while we rollback this change back.

**Comment by Quintasan** [comment]
@yosifkit @tianon can we have any input on this from you? I sure can create a `FROM` image based on this one but I think it's an overkill. Unless I promote my "fork" other people will do exactly the same and we will just end up wasting space and time
