### ISSUE TITLE
Alpine 3.19 image for ruby 3.3.1 not available in modern architechtures

### ISSUE THREAD

**Issue by woodhull** [docker-library/ruby#450]
For some reason the new images for the just released ruby 3.3.1 for Alpine is not available for arm64 or amd64, just the ancient x86 and armv6 architectures. 

Is this a bug in the build process, or have the docker image builders just not caught up with the new release?

https://hub.docker.com/layers/library/ruby/3.3.1-alpine3.19/images/sha256-25dd60e6960994df54d5d49397b48a4e36a5b3247183ef49e133d6eacc6e1084?context=explore

I checked the Docker Hub Status page and it is all 🟢.

**Comment by SocalNick** [comment]
Same, in our build:

```
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by SocalNick** [comment]
Working now...

**Comment by tianon** [comment]
Duplicate of #449
