### ISSUE TITLE
ruby:3.3.3 images don't have any platforms?

### ISSUE THREAD

**Issue by Roguelazer** [docker-library/ruby#462]
It's like #461, but rather worse; it appears that none of the 3.3.3 images published earlier today have *any* architectures present; the manifests are all totally empty:

```json
{
  "manifests": [],
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2
}
```

**Comment by tianon** [comment]
Builds are still in progress, and the index will be filled as builds finish.
