### ISSUE TITLE
Run `gem update --system $RUBYGEMS_VERSION`

### ISSUE THREAD

**Issue by nicknovitski** [docker-library/ruby#47]
I propose that rubygems be treated much like bundler, explicitly installing the latest version.  Lines like these would be added to each build:

```Dockerfile
ENV RUBYGEMS_VERSION 2.4.8
RUN gem update --system $RUBYGEMS_VERSION
```

2.4.8 is the current version of rubygems as of this post.  The lowest supported ruby version is 2.0.0, which ships with rubygems 2.0.14.  Backwards compatibility is a central goal of the rubygems maintainers, so new versions works with ruby versions at least as far back as 1.9.x.  The changes between 2.0.14 and 2.4.8 add features and fix many security vulnerabilities.

I will gladly do the typing for this, but are there any objections?

**Comment by tianon** [comment]
Seems sane -- never considered it because I didn't realize we could do
rubygems updates out of band!

We do the same thing with "pip" over in the python images, so +1 from me.
