### ISSUE TITLE
Currently it's not possible to build an Image with ruby:1.9.3

### ISSUE THREAD

**Issue by berti92** [docker-library/ruby#480]
Currently it's not possible to build or run an image with ruby 1.9.3:
```
berti@Mac-mini-von-Berti musikerseiten % sudo docker run -it ruby:1.9.3
Password:
Unable to find image 'ruby:1.9.3' locally
docker: Error response from daemon: missing signature key.
```
I tried it with an Mac Mini with M1 and on an Ubuntu Server (24.04) with amd64

I know it's an old version, but maybe you could help me to get the app of my customer get running again.

**Comment by LaurentGoderre** [comment]
An image that old isn't compatible with the more recent docker engine.

**Comment by jgzurano** [comment]
Same with `ruby:1.9.3-p551` on Ubuntu 22
```
$ docker -v
Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1

$ docker pull ruby:1.9.3-p551
Error response from daemon: missing signature key
```

Seems like this error started to affect pulls recently, I was able to build with that image a few weeks ago (Oct 30th).

I was thinking of probably rebuilding the image from scratch, but couldn't find the source in this github repo.

Anywhere I can find the old Dockerfile used for this?

Also, is there any known workarounds to this pull error?

In the meantime, will look into: https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1

**Comment by LaurentGoderre** [comment]
While there is a fix coming, you can run the following script as a temporary workaround to get the image working (requires jq and crane)

```
image=ruby:1.9.3
layers=$(crane manifest $image | jq -r '.fsLayers[].blobSum')
echo $layers | xargs -I% sh -c "crane blob ruby@% > %.tar.gz"
echo "FROM scratch" > Dockerfile
echo $layers | xargs -I% sh -c "echo 'ADD %.tar.gz .' >> Dockerfile"
docker build -t $image .
`

**Comment by tianon** [comment]
There's now a fix in place in Docker Hub for the original pulling issue (schema1 images should pull successfully again in tools which support them).

If you have a tool which does not support them and you still need to work with them, I have written https://github.com/tianon/oci-schema1 to help perform the conversion without any runtime support (`bash` + `jq` + a little `crane`).
