### ISSUE TITLE
3.4.0 GA

### ISSUE THREAD

**Issue by tianon** [docker-library/ruby#488]
As is [Ruby tradition](https://en.wikipedia.org/wiki/History_of_Ruby), 3.4.0 is extremely likely to be released/GA'd [on Christmas Day (Dec 25th)](https://en.wikipedia.org/wiki/History_of_Ruby#:~:text=Annual%20releases%20of%20the%20language%20often%20take%20place%20on%20Christmas%20Day.).  I'm filing this in advance in our last actual/official working week of 2024 to make it clear that 3.4.0 will _not_ be published on Christmas Day, and that the soonest we _might_ get to it is going to be Dec 26th (if not sometime in January, given the holiday season).  Please be patient. :heart:

(If all goes well, the GA update will get committed here by @docker-library-bot automatically, but the PR to https://github.com/docker-library/official-images will wait until one of us gets to it. :bow:)

See also https://github.com/docker-library/ruby/issues/434

**Comment by stmpjmpr** [comment]
[3.4.1 is out now](https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-1-released/).

**Comment by Vasfed** [comment]
Relevant PR seems to have some movement - https://github.com/docker-library/official-images/pull/18163

**Comment by LaurentGoderre** [comment]
Opened https://github.com/docker-library/official-images/pull/18165

**Comment by LaurentGoderre** [comment]
The build queue is particularly long because of the Debian update from Tuesday but it will be on hub soon

**Comment by Vasfed** [comment]
Most popular architectures are already on hub 🎉
