### ISSUE TITLE
Upgrading to 3.4.1 causing build issues

### ISSUE THREAD

**Issue by travisTheOrange** [docker-library/ruby#491]
We're using Github Workflows to build our Docker image and after the upgrade to [Ruby 3.4.1](https://github.com/docker-library/official-images/commit/57087ec7c483967f874efc74c35ed2c76af8d2d0) we've had issues with pull requests failing on Docker builds because of a mismatch in Ruby versions. We're using 3.3.0 yet the Docker build is using 3.4.1, causing a failure.

I'm very ready to admit we have not done something right in our Docker build logic but it has worked for us up until the aforementioned upgrade.

![Screenshot 2024-12-27 at 2 49 14 PM](https://github.com/user-attachments/assets/9a98ef16-0b3a-4d3d-9943-eb7112cf4f62)

**Comment by LaurentGoderre** [comment]
From the look of it, the issue is the gemfile expects 3.3 but the image is 3.4

**Comment by Earlopain** [comment]
I suspect you use the image without a specific version identifier (`3-bookworm`, `bookworm`, etc.), causing it to jump to the next minor version on CI.
