### ISSUE TITLE
Disable bundler warning when run as root

### ISSUE THREAD

**Issue by blackxored** [docker-library/ruby#61]
I think I've finally found the right place to put this. :joy_cat: 
Would you accept a pull request that disables Bundler's root warning by default?
I mean this warning:

```
root@5677827dcdc3:/usr/src/app# bundle
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
```

I'd be happy to add it.

**Comment by yosifkit** [comment]
Sounds good to me!  I look forward to your PR. :smile:
