### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by hdorio** [docker-library/ruby#78]
When I attempt to talk to the MailChimp API with cURL or Faraday via HTTPS from within a ruby container, I get a certificate error.

```
~$ docker run -it --rm ruby:2.2.4 curl -v https://us5.api.mailchimp.com/3.0/

   * Hostname was NOT found in DNS cache
   *   Trying 23.205.105.59...
   * Connected to us5.api.mailchimp.com (23.205.105.59) port 443 (#0)
   * successfully set certificate verify locations:
   *   CAfile: none
     CApath: /etc/ssl/certs
   * SSLv3, TLS handshake, Client hello (1):
   * SSLv3, TLS handshake, Server hello (2):
   * SSLv3, TLS handshake, CERT (11):
   * SSLv3, TLS alert, Server hello (2):
   * SSL certificate problem: unable to get local issuer certificate
   * Closing connection 0
   curl: (60) SSL certificate problem: unable to get local issuer certificate
   More details here: http://curl.haxx.se/docs/sslcerts.html

   curl performs SSL certificate verification by default, using a "bundle"
    of Certificate Authority (CA) public keys (CA certs). If the default
    bundle file isn't adequate, you can specify an alternate file
    using the --cacert option.
   If this HTTPS server uses a certificate signed by a CA represented in
    the bundle, the certificate verification probably failed due to a
    problem with the certificate (it might be expired, or the name might
    not match the domain name in the URL).
   If you'd like to turn off curl's verification of the certificate, use
    the -k (or --insecure) option.
```

Even by specifying an updated CAfile and CApath. 

Some ruby images work but some others don't, here the list

| DOCKER_IMAGE_NAME | STATE | ID |
| --- | --- | --- |
| ruby:1 | good | 4e191365190caaa044e7e59f9c8d978789a06bf88ae33e9411a18f3c8db609f7 |
| ruby:1-slim | good | 1bb4e19d518ee3103cb883f90e310e62ea2bd4418c6d81d9ffdc4c5d0516a458 |
| ruby:1-wheezy | good | 8b63b6ab5766e7ab6f5fd1b917b8aa32f1b2fdda7998b9a682576eb2c03baee3 |
| ruby:1.9 | good | 4e191365190caaa044e7e59f9c8d978789a06bf88ae33e9411a18f3c8db609f7 |
| ruby:1.9-onbuild | good | 2fbbb9562bd96fa92b1f520e3e664fa45b15bf5c2f9185012f6b9d0105cfdcf7 |
| ruby:1.9-slim | good | 1bb4e19d518ee3103cb883f90e310e62ea2bd4418c6d81d9ffdc4c5d0516a458 |
| ruby:1.9.3 | good | 4e191365190caaa044e7e59f9c8d978789a06bf88ae33e9411a18f3c8db609f7 |
| ruby:1.9.3-onbuild | good | 2fbbb9562bd96fa92b1f520e3e664fa45b15bf5c2f9185012f6b9d0105cfdcf7 |
| ruby:1.9.3-p547 | good | 4fb2a7fff2eeb15f00e9d5764b38afaa86934189e15f87cff44001617d87a713 |
| ruby:1.9.3-p551-wheezy | good | 8b63b6ab5766e7ab6f5fd1b917b8aa32f1b2fdda7998b9a682576eb2c03baee3 |
| ruby:1.9.3-slim | good | 1bb4e19d518ee3103cb883f90e310e62ea2bd4418c6d81d9ffdc4c5d0516a458 |
| ruby:1.9.3-wheezy | good | 8b63b6ab5766e7ab6f5fd1b917b8aa32f1b2fdda7998b9a682576eb2c03baee3 |
| ruby:2 | bad | 1992c3a18436850fac8c1b207cb9d4f1abbac4eaed5c3dcc0c1f91c61584a54a |
| ruby:2-alpine | good | adfa070efe1d8b21b721a8979a7040cc9e0fe055180fff12884e9ce9cee11a49 |
| ruby:2-onbuild | bad | ec892e5cf22475063317eddde233eaedd31ec1bb87c89789bf2225bc39966aa8 |
| ruby:2-slim | bad | 721e214102d854147c18a9fed9d5aab1717945d8b0f9c03b2a0d6cb66d3bc098 |
| ruby:2-wheezy | good | 71c783e6cd4dc087ea1dfb5d6842bd510f7c818addd2e03298f11906a9845168 |
| ruby:2.0 | bad | 12a82bdb2947e7428a4fc825aa0c5820c0b43e221750a3bf14ed9bda326453a1 |
| ruby:2.0-onbuild | bad | 1369cbd5a4168a286eb17690034071042ac3d39edfa40fdc46193438dc682b2e |
| ruby:2.0-slim | bad | 8249252d5f4440f401fa50734b25c4b04aa937f0864318727c810cc5266ce2fe |
| ruby:2.0-wheezy | good | 24be5ec7ff5cab305882bc628bb77945cbec94a02755ae9a06164481524aff17 |
| ruby:2.0.0 | bad | 12a82bdb2947e7428a4fc825aa0c5820c0b43e221750a3bf14ed9bda326453a1 |
| ruby:2.0.0-onbuild | bad | 1369cbd5a4168a286eb17690034071042ac3d39edfa40fdc46193438dc682b2e |
| ruby:2.0.0-p576 | good | 5322a7e894b4072f15be74993ea907e053c07817186bf77f3c39a698070bfff6 |
| ruby:2.0.0-p594 | good | 26e611387c46674d15219149f10eca6ebf5af965f5208c1cfc3c04d42be9f3fa |
| ruby:2.0.0-p598 | good | 8f7dbb94ff3d0652d441581ff9ecb16180139082d90e14b248e75743108a76db |
| ruby:2.0.0-p598-slim | good | 7e1e4ee18c949b0b38f77693f8d36f2d4568b86b38eeefb6042185a20a13d46c |
| ruby:2.0.0-p598-wheezy | good | 89f4127e85296632f0b418919f36399f0a55297b70568571989a623128e57cc5 |
| ruby:2.0.0-p643-onbuild | good | c1404381d0f20d9c25176f18b4392bbc9328cc9e43853cc15124edf7b4dab452 |
| ruby:2.0.0-p645-slim | good | f7da5e54cfb416a39910cf93afbde32f1e0172d442df7689acae99b0a141516e |
| ruby:2.0.0-p647 | good | bf45d178c1379bbcb9e15519fa95339c4e5ed239b9110fc4b9c6ac1230f38fdb |
| ruby:2.0.0-p647-onbuild | good | 80906f6b5355189c0ea578141c40649d2a9f4044f9b31aae7f62725880794235 |
| ruby:2.0.0-p647-slim | good | dfb7e0ef6abee0bcfbeda65365d644a3f338fc0ac56b120d5fe539420f55e07d |
| ruby:2.0.0-p648 | bad | 12a82bdb2947e7428a4fc825aa0c5820c0b43e221750a3bf14ed9bda326453a1 |
| ruby:2.0.0-p648-onbuild | bad | 1369cbd5a4168a286eb17690034071042ac3d39edfa40fdc46193438dc682b2e |
| ruby:2.0.0-p648-slim | bad | 8249252d5f4440f401fa50734b25c4b04aa937f0864318727c810cc5266ce2fe |
| ruby:2.0.0-slim | bad | 8249252d5f4440f401fa50734b25c4b04aa937f0864318727c810cc5266ce2fe |
| ruby:2.0.0-wheezy | good | 24be5ec7ff5cab305882bc628bb77945cbec94a02755ae9a06164481524aff17 |
| ruby:2.1 | bad | 65ba277be45f980cd7b548e4d499634f4bc3fc91074a8dca16f028bd52c5b2cd |
| ruby:2.1-alpine | good | a63d5170f9a6208569bf075932e204bb86ebd85449db48b7be5689824e60f24f |
| ruby:2.1-onbuild | bad | 52d21df0d160fb0b44fb79da46ac5ef80b62c41a9c96142f4ee4e63c7f33614d |
| ruby:2.1-slim | bad | 76f9743ad5d1ef41356da23b166279615093b305041e95837341bda17be07b05 |
| ruby:2.1.1 | NA (curl binary not found) | 1547b2edd236bbc0c3caea17c30e44f2251fb7389cd8c263ca8c19c85f5a59d1 |
| ruby:2.1.2 | good | 5c9dcf67571cedcfad7c7255bcfc925b4ab460249800b12b5b5ed5070d4fd966 |
| ruby:2.1.3 | good | a7fa59e21b49d6cea0d50720a5cff7e250845b358d0b13a12c3b85188f4d408a |
| ruby:2.1.3-onbuild | good | ea69d9feac56a78a1b46ec5c7f295eee279892228ef63a96edc4c0d5fcea3833 |
| ruby:2.1.4 | good | 39e5956c475293080715e6e29d5b03ae5d3faa0b9b8ec7440b0509f505d7960e |
| ruby:2.1.4-onbuild | good | c3197dcaf9fedb95ef1b3ac53da814ac5c639e23420850184c0584ac34aaf10c |
| ruby:2.1.5 | good | a568e2a7412e62b295a1370b4e4b2f6c78d2da60d0682788e49b8d642f880b09 |
| ruby:2.1.5-onbuild | good | e9a4822bd4ed14069fc38cf7af30094fad0bdb07b589e22863e87e0e8f02f8e5 |
| ruby:2.1.5-slim | good | 9f8e313a0d4e09a2d8f30eb68761d4fa561f59f46d8be273a2168522da9c99ac |
| ruby:2.1.5-wheezy | good | c668eb2a27194c02b3627bd3f482ae230efee60d89addfb84ce8b0755c06f742 |
| ruby:2.1.6 | good | 562266b3c4a7a7f27fb5923337a9808f63355457960cfb32f48abf64eac473dc |
| ruby:2.1.6-onbuild | good | 8a52aaac3d7bfb229ac422c3f35fa340b15b3968765dcc55e30f736e9966e173 |
| ruby:2.1.6-wheezy | good | 5d7345f32a920b29c52a4763137903a9dafe6bd2ba7573290c1a3ea13998cb54 |
| ruby:2.1.7 | good | 9b58fb9353f2ce1d353e0b66ab1686449e7e3a97552e8ab83212d5d815ecc73a |
| ruby:2.1.7-onbuild | good | 60d286a89a2eaf76c13f33b9978e77a17bca584191df2b0c7c25ec08126472d2 |
| ruby:2.1.7-slim | good | 40e296578dd327c51615ef71d841a04c2dc86d9b1e60045041d7eb683c684fde |
| ruby:2.1.8 | bad | b6e055c4567cd26f87b13b416246541b9340651e9916d7658e44b0c23edfa0dc |
| ruby:2.1.8-alpine | good | b11f4842c749a2c6e30ab54c48a7f6217dd91135b45c86e3e5dbe849a62ef7d4 |
| ruby:2.1.8-onbuild | bad | 687ac967a9727ba531887e291e7224b92feec3c93579129dad4db2000f149a70 |
| ruby:2.1.8-slim | bad | c8d3f86aa7d3a390f4db678af1f4409f9a8b890e1e02c42664f25a78a4b4ff5b |
| ruby:2.1.9 | bad | 65ba277be45f980cd7b548e4d499634f4bc3fc91074a8dca16f028bd52c5b2cd |
| ruby:2.1.9-alpine | good | a63d5170f9a6208569bf075932e204bb86ebd85449db48b7be5689824e60f24f |
| ruby:2.1.9-onbuild | bad | 52d21df0d160fb0b44fb79da46ac5ef80b62c41a9c96142f4ee4e63c7f33614d |
| ruby:2.1.9-slim | bad | 76f9743ad5d1ef41356da23b166279615093b305041e95837341bda17be07b05 |
| ruby:2.2 | bad | 9168c99105ac8e09a6d18b1ce8731be74be2b9655dca01c2d1c6614e1a41716a |
| ruby:2.2-alpine | good | 0a385e84aaf3d993f774f31f9003f46b22b53ee1de73c164c2641be0a17bf472 |
| ruby:2.2-onbuild | bad | 57e30265b8c221e2cc9d1ce52faea79752f7234beea077d0022945bc3c96f297 |
| ruby:2.2-slim | bad | 456fb6983d801a6a436e8a815ac0913e011fe7ea9c5b605a55be093d9e8e6b01 |
| ruby:2.2-wheezy | good | 71c783e6cd4dc087ea1dfb5d6842bd510f7c818addd2e03298f11906a9845168 |
| ruby:2.2.0 | good | ac90cee007593cb0401e757ea841b9b2b677ad1e2a26dac70d785ee8ffb47451 |
| ruby:2.2.0-onbuild | good | 169f6b04cf0a33ed930f7159d97b6418a7a11be98ddace18df4db3723fd6843d |
| ruby:2.2.0-rc1 | good | 869bf8ca1543f99602bfd9f3675e8ad27a71fb1f9843c6c28e82f7c2a51a8517 |
| ruby:2.2.0-rc1-wheezy | good | ba5ebb0a8f65295fb9942d0e84ff91095a59f685489d5a1869ffb6a6ac9b387a |
| ruby:2.2.0-slim | good | b56be7f8eb6a3e8aa401650f9205e8d6a6d262915750cb31350332225d9e6df5 |
| ruby:2.2.1 | good | 251617d9a570abc19797f00aa27ee0c48f66870f787292a7d7f0209eb7be7c8d |
| ruby:2.2.1-onbuild | good | 277e773888af3fad3dad9402b89ec4cd1ee2dd7358076ee19646b2c492998cd2 |
| ruby:2.2.1-slim | good | fbd623404e2fb79b7f32a9ea15cfd0901d5feb6a1540ad36666f0c74906437ff |
| ruby:2.2.2-onbuild | good | ccb2c1091def898d73a6cc2d37cfa288ff4d341cd13e728b60c300c3074e4fa6 |
| ruby:2.2.2-slim | good | c5ffcf214676821afdca8bdbb77f60ac5e4c8e2c7db4e382f9c0b1bc667ba88f |
| ruby:2.2.3 | good | 72336174e973f4147be55de74136f524d54f9017303460b14e1235e925af308c |
| ruby:2.2.3-onbuild | good | b389995ce3c15b38a462f5d2ef8398fafa2892554f4fda761b422eba4e976713 |
| ruby:2.2.3-slim | good | f32dbea11bd0e3a2852c17b4bf02343139a0a2046dc502963c3ab4ae2c30f357 |
| ruby:2.2.4 | bad | 9168c99105ac8e09a6d18b1ce8731be74be2b9655dca01c2d1c6614e1a41716a |
| ruby:2.2.4-alpine | good | 0a385e84aaf3d993f774f31f9003f46b22b53ee1de73c164c2641be0a17bf472 |
| ruby:2.2.4-onbuild | bad | 57e30265b8c221e2cc9d1ce52faea79752f7234beea077d0022945bc3c96f297 |
| ruby:2.2.4-slim | bad | 456fb6983d801a6a436e8a815ac0913e011fe7ea9c5b605a55be093d9e8e6b01 |
| ruby:2.3 | bad | 1992c3a18436850fac8c1b207cb9d4f1abbac4eaed5c3dcc0c1f91c61584a54a |
| ruby:2.3-alpine | good | adfa070efe1d8b21b721a8979a7040cc9e0fe055180fff12884e9ce9cee11a49 |
| ruby:2.3-onbuild | bad | ec892e5cf22475063317eddde233eaedd31ec1bb87c89789bf2225bc39966aa8 |
| ruby:2.3-slim | bad | 721e214102d854147c18a9fed9d5aab1717945d8b0f9c03b2a0d6cb66d3bc098 |
| ruby:2.3.0 | bad | 1992c3a18436850fac8c1b207cb9d4f1abbac4eaed5c3dcc0c1f91c61584a54a |
| ruby:2.3.0-alpine | good | adfa070efe1d8b21b721a8979a7040cc9e0fe055180fff12884e9ce9cee11a49 |
| ruby:2.3.0-onbuild | bad | ec892e5cf22475063317eddde233eaedd31ec1bb87c89789bf2225bc39966aa8 |
| ruby:2.3.0-slim | bad | 721e214102d854147c18a9fed9d5aab1717945d8b0f9c03b2a0d6cb66d3bc098 |
| ruby:alpine | good | adfa070efe1d8b21b721a8979a7040cc9e0fe055180fff12884e9ce9cee11a49 |
| ruby:latest | bad | 1992c3a18436850fac8c1b207cb9d4f1abbac4eaed5c3dcc0c1f91c61584a54a |
| ruby:onbuild | bad | ec892e5cf22475063317eddde233eaedd31ec1bb87c89789bf2225bc39966aa8 |
| ruby:slim | bad | 721e214102d854147c18a9fed9d5aab1717945d8b0f9c03b2a0d6cb66d3bc098 |

As a side note, an old ruby:2.0.0 image still on my local machine created 4 month ago (049270d240705c308523a1d73f0988646982389a294246ca31a3c5a2a415bd2c) works but the current image (12a82bdb2947) doesn't

**Comment by hdorio** [comment]
The issue seems to come from upstream, in image debian:jessie where GTE_CyberTrust_Global_Root.crt was removed and openssl 1.0.1 is not reading alternate certificate chains correctly

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774882

**Comment by yosifkit** [comment]
Looks like this was fixed in May 2016. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774882#57 for the specific Debian version numbers that contain the fix.  Closing old issue since the latest images work.
