### ISSUE TITLE
Timeout during download of ruby:2.3.1

### ISSUE THREAD

**Issue by Gitward** [docker-library/ruby#80]
When I'm trying to install the image `ruby:2.3.1` using `sudo docker -D run ruby:2.3.1` I always get a timeout: `docker: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).`

```
Unable to find image 'ruby:2.3.1' locally
2.3.1: Pulling from library/ruby
51f5c6a04d83: Already exists 
a3ed95caeb02: Downloading 
7004cfc6e122: Pull complete 
5f37c8a7cfbd: Pull complete 
8ad7684cace4: Pull complete 
4ea23a99281b: Downloading 
19d7d9a19397: Download complete 
b63605252a71: Download complete 
f08c166cb151: Download complete 
docker: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

One thing that always happens is that the step `4ea23a99281b` is in state `Downloading `. The step `a3ed95caeb02` is sometimes `Downloading `, sometimes `Download complete` and sometimes `Waiting`.

This also happened when trying to run `ruby:2.1` and when pulling it `pull` (`sudo docker -D pull ruby:2.1`). I also had the error: `docker: net/http: TLS handshake timeout.`

Pulling `ruby:2.2` worked.
Now I can also download the other tagged versions.

I'm running `Docker version 1.11.2, build b9f10c9` on `Ubuntu 16.04 LTS`; My internet connection is quite slow - the timeouts occurred 7-15 minutes after starting the download (took me 5 hours already).

**Comment by yosifkit** [comment]
That is an issue with the hub and not anything with the image; I was able to `docker pull` it just a few minutes ago.  If you are still having issues pulling things from the docker hub you should probably check with them.
