### ISSUE TITLE
compile with clang

### ISSUE THREAD

**Issue by tonytonyjan** [docker-library/ruby#84]
Ruby compiled with Clang is claimed 8% faster than with GCC 4.9 and 44% faster than with GCC 4.7.2. It would be wonderful to have a clang compiled version. Is this feature possible in the future?

**Comment by yosifkit** [comment]
If you are talking about [this post](http://cirandas.net/brauliobo/blog/ruby-compiled-with-clang-is-8-faster-than-with-gcc-4.9-and-44-faster-than-with-gcc-4.7.2) from 2014, then you should also look at [this post](https://www.p8952.info/ruby/2014/12/12/benchmarking-ruby-with-gcc-and-clang.html) that has a more in-depth comparison.

As of that post, it looks like gcc 4.9 was the clear winner (though only marginally).  Which is the version currently used in the Debian Jessie based images.
> 4\. The latest version of GCC (4.9) is ahead by a clear margin.

> Of course the standard disclaimers apply. Benchmarking correctly is hard, you may not see the same results in your specific environment, do not immediately recompile everything in prod using GCC 4.9, ect.

Given that ruby doesn't specifically recommend a compiler and there is not really any gain in changing, I think that we should stick with gcc for now.

**Comment by Moghedrin** [comment]
A stale issue, going to go ahead and close this.
