### ISSUE TITLE
onbuild with additional header dependencies?

### ISSUE THREAD

**Issue by kaihendry** [docker-library/ruby#85]
I'm trying to Dockerize an application that requires Maxmind headers IIUC.

> An error occurred while installing maxmind_geoip2 (0.0.8), and Bundler cannot
> continue.
> Make sure that `gem install maxmind_geoip2 -v '0.0.8'` succeeds before bundling.
> The command '/bin/sh -c bundle install' returned a non-zero code: 5

How do I incorporate them ontop of a standard image like what you provide? This doesn't appear to work:

```
FROM ruby:onbuild
RUN add-apt-repository ppa:maxmind/ppa && \
apt-get update && \
apt-get install libmaxminddb0 libmaxminddb-dev mmdb-bin -y
```

**Comment by yosifkit** [comment]
Yeah, `onbuild` images are very limited.  If you need additional customization (like apt dependencies) before the `bundle install` then you have to instead copy all the lines from the onbuild dockerfile to your own (removing the `ONBUILD` directive), swap to `FROM ruby:2.3`, and then customize your ordering to run your `apt-get install` before the `bundle install`.

**Comment by kaihendry** [comment]
Ok, thanks will work from https://github.com/docker-library/ruby/blob/master/2.3/onbuild/Dockerfile

**Comment by yosifkit** [comment]
Looks like the Maxmind library is packaged in Debian under `libgeoip-dev`: https://packages.debian.org/jessie/libgeoip-dev.

**Comment by kaihendry** [comment]
Thanks, I'm using ruby:alpine and `libmaxminddb libmaxminddb-dev` which builds fine.

But... the entrypoint is `irb`. I'm wondering next how to run puma et al. Sorry, I'm a rails newbie. Any pointers would be great.

**Comment by yosifkit** [comment]
That is just the `CMD` for the interactive ruby interpreter, which is easily overridden in the Dockerfile or when doing docker run.  I think `rails s` is the normal starting of rails applications.  You might want to look at [redmine](https://github.com/docker-library/redmine/tree/a825346f46c284ea84658c8b86b8b2b120e5f51c/3.3) for an example of using `tini` or `dumb-init` if you start to run into the zombie reaping problem (http://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html).

```
CMD ["rails", "s"]
or 
docker run my-app rails s
```

**Comment by yosifkit** [comment]
It seems like this was resolved. Closing.  If you feel this was closed in error, please feel free to comment.
