### ISSUE TITLE
Using http instead of https to get ruby

### ISSUE THREAD

**Issue by Dbz** [docker-library/ruby#86]
Hello,

For security purposes, we always need to use https when fetching ruby. In the dockerfile, you get ruby from `http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.gz`.

May I make a pull request to switch this to https (I'd like to contribute)? If not, what is the reason that you are using http over https?

Thank you for your time, and I appreciate the ruby image!

**Comment by yosifkit** [comment]
Oh. That seems fine. I think we had not noticed that their server was available via https.

**Comment by yosifkit** [comment]
Fixed in #87
