### ISSUE TITLE
Tag latest not found in repository docker.io/library/ruby

### ISSUE THREAD

**Issue by dieuit07** [docker-library/ruby#90]
Hi everyone, when build a dockerfile.

```
FROM ruby:latest
MAINTAINER ...
```
I receive some info:
```
Pulling repository docker.io/library/ruby
bfe1e909440a: Download complete 
33a372e3ad95: Download complete 
1230b07f5c40: Download complete 
0ebd84a329dd: Download complete 
...
Pulling repository docker.io/library/ruby
Tag latest not found in repository docker.io/library/ruby
```

I try with run in console 'docker pull ruby' , it through the same error.

Is it a problem of docker server?

**Comment by wyaeld** [comment]
Its not a problem, you have to be more specific about which version and variant you want.  See list of tags here
https://hub.docker.com/r/_/ruby/

Other languages like python seem to be similar

**Comment by yosifkit** [comment]
We have `latest` tags for all the official images. Currently the ruby image shows this on the hub page `2.3.1, 2.3, 2, latest (2.3/Dockerfile)`.  Being unable to pull usually points to a Docker Hub problem, but every once in a while restarting your local docker daemon can fix it.

**Comment by tianon** [comment]
Indeed, can't seem to reproduce so must have been environmental or a temporary hiccup:
```console
$ docker pull ruby:latest
latest: Pulling from library/ruby

386a066cd84a: Already exists 
75ea84187083: Already exists 
88b459c9f665: Already exists 
1e3ee139a577: Already exists 
741de17843a5: Pull complete 
7b91d9bcfd6e: Pull complete 
f4906808c869: Pull complete 
e9976164e43f: Pull complete 
Digest: sha256:a5ebd3bc0bf3881258975f8afa1c6d24429dfd4d7dd53a299559a3e927b77fd7
Status: Downloaded newer image for ruby:latest
```
