### ISSUE TITLE
bundler 1.13.7

### ISSUE THREAD

**Issue by s1l3nt** [docker-library/ruby#98]
https://rubygems.org/gems/bundler/versions/1.13.7

**Comment by yosifkit** [comment]
done! https://github.com/docker-library/ruby/commit/b2f84d6b678e22d60995398746d14df79ab6b850, https://github.com/docker-library/ruby/commit/a684313c1187b2955e0f822b9ed7cc22f50c0c45, https://github.com/docker-library/ruby/commit/64121ac0a34d07ff1c7341651f8775476cba6c41, and https://github.com/docker-library/ruby/commit/22fcd2eda0bb8cab0ca674881c5112e8627b3d43
